### ISSUE TITLE
model.where(...)[(intermediate value) -  error

### ISSUE THREAD

**Issue by GlauberF** [feathersjs/feathers#1035]
### featherjs version 3.5.0

In my local development, everything is working, but in production this gives the following error

![captura de tela de 2018-10-03 18-01-06](https://user-images.githubusercontent.com/11314585/46438702-efc9b280-c734-11e8-8b66-023fb97592bf.png)

**Comment by daffl** [comment]
Please provide additional information from the issue template:

### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by GlauberF** [comment]
solved :)
it was deploy error
