### ISSUE TITLE
Asynchronous publishing of events

### ISSUE THREAD

**Issue by palamed** [feathersjs/feathers#1068]
Calling publisher for specific event on service causes request to last longer. 
This is example from docs:

// Publish the `created` event to admins and the user that sent it
```
app.service('users').publish('created', (data, context) => {
  return [
    app.channel('admins'),
    app.channel(app.channels).filter(connection =>
      connection.user._id === context.params.user._id
    )
  ];
});

```
If filter function is more complex and  there are lot of users, create method service will not finish until  callback publisher end filtering and send event. Is there a way to to perform publish method and filter asynchronously and let create service to finish its job?

**Comment by daffl** [comment]
Events always run asynchronously so the `create` method will finish before/while the publisher runs. Ideally you should create the proper channels once on `login` or `connection` so that you don't have to call `filter` every time especially if it is a complex filter operation. The better way to implement the example above would be:

```js
app.on('login', (payload, { connection }) => {
  if(connection && connection.user) {
    app.channel(connection.user._id).join(connection);
  }
});

app.service('users').publish('created', (data, context) => {
  return [
    app.channel('admins'),
    app.channel(context.params.user._id);
  ];
```

**Comment by palamed** [comment]
Thank you very much for info that events run asynchronously.  I solved my problem by providing async function to publish.
