### ISSUE TITLE
Calling app.authenticate() Multiple Times Clientside to Check Auth

### ISSUE THREAD

**Issue by amxmln** [feathersjs/feathers#1187]
Can you use [app.authenticate()](https://docs.feathersjs.com/api/authentication/client.html#appauthenticate) multiple times on the client side to check if the user can navigate to a page that requires login?

The docs state that it should only be called once at the start-up of the application, but as @issy123 mentioned in [this issue](https://github.com/feathersjs/feathers/issues/1177) using it multiple times works fine.

**Comment by daffl** [comment]
If it is the same application (as in an SPA that runs within a single page load) you should store the result of `app.authenticate()` somewhere where it is accessible for every part of your application that needs to check it. If the page is changed (as in browser reload) `app.authenticate()` can be called again.

**Comment by issy123** [comment]
Perfect answer!

**Comment by amxmln** [comment]
@daffl Yeah that’s how I thought the function was to be used, however storing the response in the client isn’t secure for validating a user’s authentication because it could be tampered with (see the issue I linked above).

**Comment by daffl** [comment]
That doesn't matter because it will be validated on every request on the server anyway. If it is invalid, any request that requires authentication will fail.

**Comment by amxmln** [comment]
For calling services that is true, but it’s not good for securing client-side routes, which was my original issue.

**Comment by daffl** [comment]
I'm not exactly sure what you are concerned about. The client side logic shouldn't contain any sensitive operations (that isn't double checked by the server) anyway so even if someone went through the effort of somehow successfully changing their privileges on the client any unauthorized request to the server will still fail. What should happen in your client side application is either

a) Call `app.authenticate()` once the application is loaded and store user information you need and check it whenever user navigates to a protected route
b) If user navigates directly to a protected page/route you need to call `app.authenticate()` anyway (since your application needs to load) and check the information just as in a)

**Comment by amxmln** [comment]
I feel like protecting a client-side route so that it cannot be accessed without valid authentication is a common enough task—although that might be my own inexperience showing. For example if I have an /admin route, I wouldn't want somebody who is not an logged in to see it even though they couldn't actually call any of the services because they have no Auth.

I guess since `app.authenticate()` can't be used, I'll do it with a simple service that checks where a user is authenticated on the server.

**Comment by daffl** [comment]
How to get the user information after `app.authenticate()` [is documented here](https://docs.feathersjs.com/api/authentication/client.html#complete-example). With that information you can do exactly what you want and protect the routes the user shouldn't see. A separate service works, too of course.

**Comment by daffl** [comment]
That totally works but I still think you might be worrying about the wrong thing here. Client side JavaScript code is always visible for anybody who downloaded it so if someone really wanted to they can always find a way to work around it (in your case e.g. by "faking" the auth-check service response).

That's why an API server always has to double check if the client is actually allowed to make a request. So worst case they'd see the admin interface on the client but wouldn't be able to retrieve any of the protected data.

**Comment by amxmln** [comment]
You’re right, maybe I have been overthinking this too much. :thinking: 

Thank you very much for your time and this framework. I’ve really been enjoying Feathers so far. :+1:
