### ISSUE TITLE
teardown method on services

### ISSUE THREAD

**Issue by sepehr-laal** [feathersjs/feathers#1200]
is there a teardown mechanism implemented for service instances? I can have a `.setup(app, path)` method to initialize things but I cannot seem to find a documented way to teardown the service when app's `close()` is called. Is this possible?

**Comment by daffl** [comment]
Since it is not possible to unregister a service during runtime, I don't think this is necessary yet. Just loop through [app.services as shown in the documentation](https://docs.feathersjs.com/api/application.html#services) when you want to close the application and call the method you need if it exists:

```js
const servicePaths = Object.keys(app.services);

servicePaths.forEach(path => {
  const service = app.service(path);

  if (typeof service.destroy === 'function') {
    service.destroy();
  }
});
```

**Comment by sepehr-laal** [comment]
sounds reasonable. thanks for your response.
