### ISSUE TITLE
Data missing in Authentication.Remove

### ISSUE THREAD

**Issue by TriangularCube** [feathersjs/feathers#1217]
I have a standard authentication setup straight from the Chat app with the exception of using ES512 instead of HMAC.

Everything works fine on Create in the service, authorization works and a token is returned using both JWT and local strategies.

Invoking DELETE from Postman however returns a "No auth token" error when sending token in body, and "PEM_read_bio_PUBKEY failed" when sending via header. Same token that otherwise works when POSTing.

When I log *context* to the console in a hook there is no *data*, nor anything identifiable in *params* unless I sent the token via header.

Is the Authentication service's Remove call just not used ever, or am I missing something?

**Comment by marshallswain** [comment]
The remove service basically does nothing, by design.  You can consider it to be an abstract method on the authentication service.  It's only there for if you plan to implement some functionality on the server during user logout.  On the client, you can just delete the JWT and the user is basically logged out.

**Comment by TriangularCube** [comment]
I see. I was hoping to pull the token out to perform some sort of token blacklisting, but if I have to send it through the header that's what I'll do. Thanks!
