### ISSUE TITLE
Install sentry on api

### ISSUE THREAD

**Issue by GlauberF** [feathersjs/feathers#1268]
Hello,
In all my applications I use sentry for error collection, what would be the best way to insert sentry in featherjs.

Taking into account the image below.
![Captura de Tela_selecionar área_20190402173733](https://user-images.githubusercontent.com/11314585/55434692-881ee380-556e-11e9-8b21-436ad6a47e7e.png)

**Comment by marshallswain** [comment]
@GlauberF Since Express is what's running under the hood, you can use Sentry in exactly the same way as described in that image (for rest).  I would imagine that Sentry would have some way for you to manually do with Sockets what their Express middleware does.  Do they have any low-level methods for you to tap into?

**Comment by subodhpareek18** [comment]
This is how I use it
```js
import * as Sentry from '@sentry/node';

export const app = feathers();
const env = app.get('env');

const isProd = process.env.NODE_ENV === 'production';

if (isProd) {
  Sentry.init({
    dsn: 'https://0f7fc1b39c2f44efbb51f8643f4eb9c1@sentry.io/1330904'
  });
  app.use(Sentry.Handlers.requestHandler());
}

app.configure(hooks());
app.configure(rest());

app.use(cors());
app.use(helmet());
app.use(compress());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

app.configure(services());
app.hooks(appHooks());

if (isProd) {
  app.use(Sentry.Handlers.errorHandler());
}

app.listen(8000);
```

**Comment by matiaslopezd** [comment]
Maybe can use in `src/hooks/log.js`
