### ISSUE TITLE
You should be able to revoke JWT's

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers#1336]
At some point we need to implement this I think. It's not a massive rush though as this can be left to the developer. It's also not super trivial but if you are using HTTPS, because we don't expose the JWT in the query string, it's not very likely that it would be maliciously stolen.

See https://auth0.com/blog/2015/03/10/blacklist-json-web-token-api-keys/ for details.

**Comment by averri** [comment]
This is a good discussion. Unfortunately, there is nothing in the JWT specification, the [RFC 7519](https://tools.ietf.org/html/rfc7519), that describe the revocation mechanism.

It's relatively easy to implement such revocation mechanism, and this implies in loosing the statelessness aspect of JWT, as the server will have to maintain a list of the revoked JWTs.

A common approach for revoking JWTs is to store the `user ID`, the `jti ` claim, the `exp` claim and  the `device ID` (an unique fingerprint of the device - a browser in the desktop, or a mobile device). The server needs to store these data until the expiration, which is controlled by the `exp` claim. So it's possible to calculate the amount of data to be stored in the back-end, possibly a key-value distributed database, considering a particular statistical distribution of the revocations. The amount of data will be stable for a particular statistical distribution depending on the value of the `exp`. The use of the `device ID` is optional, but this introduces a fine control of the logout mechanism, it's possible to logout a user from a particular device or all devices.

**Comment by KidkArolis** [comment]
> **It worth mentioning**: using this mechanism invalidates the benefits of JWT.

By default in Feathers, and in general any framework really, the user object is already fetched from the datastore on each request. This is done because most often the authorization logic requires looking at the user object (e.g. organisationId, role, etc.). Checking some extra column for expiration details (either to disallow invalidated token or to force user to relogin every 30 days) comes at no extra cost in that case.

This is just a default behaviour of course and you could avoid querying the user on each request if you have a high load api.

**Comment by daffl** [comment]
Documentation for this has been [added to the Cookbook](https://docs.feathersjs.com/cookbook/authentication/revoke-jwt.html).
