### ISSUE TITLE
MySql Adapter

### ISSUE THREAD

**Issue by valentinLecorps** [feathersjs/feathers#139]
Do you know where i can found a connector to bind my feathers applications with my MySql database?
I read that "We support MongoDB, Postgres, and MySQL out of the box." on your website but i can't found it...

Thanks

**Comment by daffl** [comment]
@ekryski is holding them hostage on his hard drive right now ;) We will put them up over the weekend.

**Comment by valentinLecorps** [comment]
Alright, thanks you :)

**Comment by ekryski** [comment]
I just finished updating all the other adapters. Next one up is MySQL. Shouldn't take too long. I'll post again when it's up.

**Comment by marrone** [comment]
Hey, feathersjs looks really promising... is MySQL support still being worked on? I see you've created this repo linked in the docs, https://github.com/feathersjs/feathers-mysql, but still empty. I assume it is still in progress and not abandoned? 

Thanks for this

**Comment by ekryski** [comment]
@marrone It's definitely on the docket. I've started it locally but it's not yet ready. I've been pretty busy with work and family lately. But it's totally not abandoned! :smile:

**Comment by seanodotcom** [comment]
Any update on the MySQL connector? Just finished the intro tutorial and am pretty excited about getting started... this is the final piece.

**Comment by daffl** [comment]
@seanodotcom @ekryski has been slammed with work lately so I'm not sure. Would you be interested in helping out if he manages to put up the basic CRUD skeleton? Any help would be very much appreciated.

**Comment by VladShcherbin** [comment]
Wow, promises dated by July... Really 'promising' framework.

**Comment by daffl** [comment]
You know this is open source right? I know of people that wrote their own internally and it seems to be working just fine. There is nothing holding you back doing the same and sharing it with everybody. We're more than happy to help out.

**Comment by VladShcherbin** [comment]
@daffl sure, it is okay, if some functionality comes after some time, but saying it will be ready on the weekend and the weekend was almost half a year ago is a big turn around when discovering the framework.

**Comment by ekryski** [comment]
@VladShcherbin Sorry it has taken so long. We're not able to work on Feathers full time. In fact, most of the work is done after work in the late evenings or weekends after chores have been finished, bills have been paid, diapers have been changed, etc. If you need a MySQL connector ASAP you are more than welcome to write it or pay us to write it. Since I gather that is not the case, please be patient.

We have lives outside of open source and really are trying our best to get this stuff out as soon as we can with the best quality. We've been working on SQL adapters over the last couple weeks and truthfully should have first versions up within a week. You can follow the progress on https://github.com/feathersjs-knex as that is the underlying library.

Our bad, for saying they were ready when they weren't. That won't happen again.

In the mean time, @daffl has made a very fair point. We are always open to pull requests. In fact, you'll see that our PR's get closed much faster than when we have to write stuff ourselves :wink:.

**Comment by daffl** [comment]
Instead of making a database specific adapter we decided to make adapters per ORM. Here are the ones that support MySQL:

- https://github.com/feathersjs/feathers-knex
- https://github.com/feathersjs/feathers-sequelize
- https://github.com/feathersjs/feathers-waterline (still in the works)

**Comment by ekryski** [comment]
I think we can close this now. Plenty of options here! :smile:
