### ISSUE TITLE
Getting user and 'authenticated' in auth service 'after' hook (v4)

### ISSUE THREAD

**Issue by jnardone** [feathersjs/feathers#1427]
### Steps to reproduce

Trying out authentication v4 and have run into a problem.

The new auth implementation does not require (or allow) the use of the 'authenticate' hook on the authentication service itself.

However, we have a bunch of "after" hooks on the authentication service that need access to:
1) was the user authenticated
2) the user object

These are in `hook.params` when the hook is used, but for hooks on the authentication service itself, they are not.  

Is there a reason that the `authenticate` hook is explicitly disallowed on the authentication service?  Is there a way to access the authentication result and user object in `after` hooks?

### Expected behavior
Ideally, backwards-compatible access to `hook.params.authenticated` and `hook.params.user` in `after` hooks

### Actual behavior
It looks like there might be a user in `hook.result` we can use, but I can find no equivalent of `authenticated`.  (Is this just the presence of an accessToken in `hook.result`?)

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
4.0-pre.3

**NodeJS version**:
10.16.0

**Operating System**:
macos

**Comment by daffl** [comment]
The reason is that the `authenticate` hook now only has one explicit way to be triggered which is by setting `params.authentication`. The behaviour for the authentication service is to authenticate against the service method `data`. It leaves a lot less room for error (and bugs) when those two things are handled separately.

The `authenticated` in this case is probably redundant. You can safely assume that authentication was successful when no error was thrown (and your hook gets executed).  As you pointed out all authentication information from the service is now in available `context.result`. A hook to make it fully backwards compatible by setting those properties could look like this:

```js
context => {
  context.authenticated = true;
  context.params = {
    ...context.params,
    context.result
  }

  return context;
}
```
