### ISSUE TITLE
[v4] getting error when call api to get list of my 'messages' service (no such column: messages._id)

### ISSUE THREAD

**Issue by hunght** [feathersjs/feathers#1464]
### Steps to reproduce
1- create an app 
2- create service: feathers generate messages (configure Sequelize and SQLite)
3- call API to get a list of messages. get error:

```
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
(node:5496) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
info: Feathers application started on http://localhost:3030
Publishing all events to all authenticated users. See `channels.js` and https://docs.feathersjs.com/api/channels.html for more information.
error: GeneralError: SQLITE_ERROR: no such column: messages._id
```

**Comment by hammooooody** [comment]
code please

**Comment by hunght** [comment]
@hammooooody there is no particular code. I don't change anything just the code generated from the command. Pls check steps to reproduce I sent

**Comment by hammooooody** [comment]
From what it looks like you have created a feathers server with the name 'messages' rather than creating a service within the app called 'messages'
`feathers generate messages` is used to create the app not the service.
To avoid naming confusion go into a fresh folder and 
1. `feathers generate myserver` or whatever name you want.
2. `feathers generate service`
3. follow the cli steps provided.

**Comment by hunght** [comment]
yeah it worked now!, should be my fail because I send _id to the request
