### ISSUE TITLE
easy way to authenticate both REST and socket.io?

### ISSUE THREAD

**Issue by jnardone** [feathersjs/feathers#1482]
Prior to v.4 we could authenticate with socket.io and then "share" the token from one with the other e.g. `restApp.set('accessToken', socketApp.accessToken);` and thus not require two round trips to authenticate both transports.

Is there a way to do this in v4? We have enough services that require one vs. the other that we can't simply pick one or the other.

**Comment by daffl** [comment]
On the client once authenticated, the access token will be available in [app.get('authentication')](https://crow.docs.feathersjs.com/api/authentication/client.html#app-get-authentication):

```js
const { accessToken } = await app.get('authentication');
```

**Comment by jnardone** [comment]
If I authenticate through one transport is that enough to use other transports? Or does each treansport maintain its own state?

**Comment by jnardone** [comment]
Ok, so no, authenticating through one transport maintains state independent of another.  What I'd like to do is authenticate once, via any transport, and then the other transports use that (shared) state so I don't have to call client.authenticate for each type.  But I realize that could be difficult.  Just trying to save a 2nd round trip.

**Comment by daffl** [comment]
Websockets *have* to explicitly authenticate by calling `app.authenticate()` on the client or sending the `socket.emit('create', 'authentication', authData)` event in order to attach their information to the socket. You could re-use that `accessToken` in a REST client by setting `Authorization` header manually using [params.headers](https://crow.docs.feathersjs.com/api/client/rest.html#params-headers) but even re-authentication that client with the `accessToken` obtained from the socket authentication should just return the same one anyway (and set up the proper client side state with all the authentication information). Will indeed require two round-trips but usually that should only happen once during application load (which ideally won't happen too often).

**Comment by jnardone** [comment]
No problem.  Thanks.

**Comment by jnardone** [comment]
Just a follow-up on this from way back in case anyone comes looking for it.

If you need to authenticate both socket and REST:
1) authenticate socket first
2) if it returns an access token, set the access token for REST and then call .reAuthenticate(true)

e.g.

```
const socketauth = await socketApp.authenticate(creds);
if (socketauth.accessToken) {
  await restApp.authentication.setAccessToken(socketauth.accessToken);
  const restauth = await restApp.reAuthenticate(true);
}
```
