### ISSUE TITLE
All feathersjs packages as one dependency

### ISSUE THREAD

**Issue by duurland** [feathersjs/feathers#1490]
In order to avoid bloating my package.json file I'd prefer to add all featherjs packages as just one dependency, then import whatever I need myself. 

Unless I'm missing something obvious, this is not currently possible?

For example
```js
import { feathers, authentication, express, errors, ...etc} from 'feathersjs';
```

Instead we need to install them all
```
    "@feathersjs/authentication": "^4.3.0-pre.1",
    "@feathersjs/authentication-local": "^4.3.0-pre.1",
    "@feathersjs/authentication-oauth": "^4.3.0-pre.1",
    "@feathersjs/configuration": "^4.3.0-pre.1",
    "@feathersjs/errors": "^4.3.0-pre.1",
    "@feathersjs/express": "^4.3.0-pre.1",
    "@feathersjs/feathers": "^4.3.0-pre.1",
    "@feathersjs/socketio": "^4.3.0-pre.1",
    etc...
```

My first thought was just to add this repo as a dependency, but as the `version` field in the package.json is omitted it can't be installed.

Possible solutions:

A) Add a `version` field to this repo package.json (preferably also a `main` function exporting all existing packages), so we can add this repo as a dependency.

B) Create a new package exporting all existing packages, similar to `@feathersjs/client` but not just for the client, for example `@feathersjs/all`.

Am I missing something?
Thoughts?

**Comment by daffl** [comment]
This is intentional and and result of the modular structure in which Feathers has been built. It is better to bloat a package.json than installing and pulling in dependencies you don't need (especially for client side builds). This will be more so important in the future with more framework integrations (e.g. Koa or native HTTP2 instead of Express) and other optional core modules.
