### ISSUE TITLE
client-side event for expired auth token? (v4)

### ISSUE THREAD

**Issue by jnardone** [feathersjs/feathers#1523]
Is there an event or a way to check if the existing accessToken has expired on the *client*?

I don't want to make a round trip, I just want to know if the current token's `exp` has passed.  I thought there was a way to do this in the auth client but I am failing to find it when digging through the code.

I know I could grab the accessToken and parse it myself, but it felt like somewhere else in the client this might already be happening?

**Comment by daffl** [comment]
This is not happening anymore. Adding the client side JWT library was not necessary in the new client since the server returns all the information a client may need. The additional round-trip to the server could also verify additional validity (e.g. if the token has been blacklisted or check the validity against the server instead of the browser time).

You can of course parse it yourself but letting the server handle it by default made things way less complicated and more flexible.

**Comment by jnardone** [comment]
No problem.  Yeah, we pulled in `jwt-decode`; we wanted to be able to pull out the expiration time (`exp` claim) of the token, so we can take client actions without a round-trip for a better experience with about-to-expire/expired tokens.
