### ISSUE TITLE
Feature Request: TypeORM

### ISSUE THREAD

**Issue by Immortalin** [feathersjs/feathers#1561]

**Comment by marshallswain** [comment]
Looks like somebody has already started at least thinking about this https://github.com/declank/feathers-typeorm

**Comment by osman-mohamad** [comment]
@marshallswain the repository is deleted. any other plugin to support use typeorm with feathersjs ?

**Comment by marshallswain** [comment]
Not that I'm aware of.  I suggest making one by using the generator to get you started.

**Comment by fullofcaffeine** [comment]
+1

**Comment by osman-mohamad** [comment]
@marshallswain thank you.

**Comment by rfclib** [comment]
Any updates on this feather?

**Comment by daffl** [comment]
The TypeScript support for Feathers schema https://github.com/feathersjs/schema#typescript will support a lot of this without being tied to a specific ORM.

I am going to close this issue since it has been a while, I don't plan on addressing this and it does not look like anybody is interested in creating an adapter for TypeORM.

**Comment by olosegres** [comment]
Here is draft of feathersjs to typeorm adapter (raw, poorly tested code, with patched order part, but it works) 
https://gist.github.com/olosegres/3c53eff66a97d58a627386f56a79ffc1
