### ISSUE TITLE
eventMappings of undefined

### ISSUE THREAD

**Issue by PowerMogli** [feathersjs/feathers#1592]
Since update to feathers v4 it happens irregular that we get the following error when executing feathers:

"... calling eventMappings of undefined..."

We checked your code but we cant understand why this should happen?!

**Comment by daffl** [comment]
Hi there! We are happy to help but we need more information about your problem.

### Error message

Are you getting an error message?

### Steps to reproduce

__The best way to get help is to share a GitHub repository or code snippet with the minimal setup to reproduce your issue.__

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by PowerMogli** [comment]
We have no clue how to reproduce this exception. So no, we cant provide you an example or code snippet to reproduce it.  All we know is that this exception seems for us to be generated by socket.io-client. But only in 1 of 10 times.

**Comment by daffl** [comment]
Unfortunately this can really be anything from a browser plugin that's doing something weird to a race condition in your application. The minimum information to even start looking into this would be

- A complete stack trace and line number with a reference to the actual code on GitHub
- The users browser and ideally browser configuration

**Comment by PowerMogli** [comment]
There is no browser in touch. This is a connection between two (micro-)services using socket.io-client to talk to each other

**Comment by alexchao** [comment]
FWIW, we got this error when we forgot to use `new` when throwing a feathers error in a hook.

```js
// instead of
throw new BadRequest('Some message')

// we did this
throw BadRequest('Some message')
```

**Comment by bertho-zero** [comment]
https://runkit.com/embed/qy0t7jhwxt5i

It is true that an error throwing without `new` gives `undefined`.

**Comment by alexchao** [comment]
Ah yes, well, that would explain it. 😅
