### ISSUE TITLE
How to verify if JWT is valid on authentication-client

### ISSUE THREAD

**Issue by averri** [feathersjs/feathers#1651]
This is a question:

How to verify if the JWT is valid on the client side? There is a method for getting the JWT - `app.authentication.getAccessToken()` but I haven't found any method for verifying if the token is valid.

API version:
- "@feathersjs/authentication-client": "^4.3.7",

**Comment by daffl** [comment]
This is done by the server and should not be necessary to do explicitly on the client. There is the option to decode and inspect the JWT with the [jwt-decode](https://www.npmjs.com/package/jwt-decode) library though:

```js
const { accessToken } = await app.get('authentication');
const decoded = jwt_decode(accessToken);

console.log(decoded);
```

**Comment by averri** [comment]
Thanks @daffl! I have noticed that the client API `getAccessToken` return null when the token is invalid (I have tested issuing a JWT with short expiry time). This is sufficient to let the UI to know when the token is expired.

**Comment by KrishnaPG** [comment]
@averri From the source code of `getAccessToken` it does not seem to validate the token before returning. Wondering how you were able to achieve the `null` on expiry. Are you sending the token to server to actually verify and reset it? Below is the source code ref:
https://github.com/feathersjs/feathers/blob/22f254a8d6b016c70608ddbf23b3c52742bea239/packages/authentication-client/src/core.ts#L103-L112

Can @daffl or others from the Feathers team confirm if this is an expected behavior (i.e. `getAccessToken` automatically returns `null` for expired token?)

If not, it would be great to have such functionality and also an event on the app when the token expires would be very valuable.
