### ISSUE TITLE
events is imported by node_modules/@feathersjs/feathers/lib/events.js, but could not be resolved

### ISSUE THREAD

**Issue by mylastore** [feathersjs/feathers#1679]
I am trying to set up the feathers client side with the code below but getting the error about.
Node v10.16.3
Using sveltejs/sapper on client

```
import feathers from '@feathersjs/feathers';
import socketio from '@feathersjs/socketio-client';
import io from 'socket.io-client';
import auth from '@feathersjs/authentication-client';

const socket = io('http://localhost:3030', {
    transports: ['websocket'],
    forceNew: true
});
const client = feathers();

// Setup the transport (Rest, Socket, etc.) here
client.configure(socketio(socket));

// Available options are listed in the "Options" section
client.configure(auth({
    storage: window.localStorage
}));

export default client;
```

**Comment by daffl** [comment]
Hi there! We are happy to help but we need more information about your problem.

### Error message

Are you getting an error message?

### Steps to reproduce

__The best way to get help is to share a GitHub repository or code snippet with the minimal setup to reproduce your issue.__

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by mylastore** [comment]
I am user sapper/svelte for client  node v 10.16.3 I getting this error on the chrome developers console 
```Uncaught TypeError: Failed to resolve module specifier "events". Relative references must start with either "/", "./", or "../".``` and this o my intellij terminal 
```'events' is imported by node_modules/@feathersjs/feathers/lib/events.js, but could not be resolved – treating it as an external dependency
'events' is imported by commonjs-external-events, but could not be resolved – treating it as an external dependency
 ```

**Comment by daffl** [comment]
`events` is marked as a dependency of `@feathersjs/feathers` in its `package.json`. If it can't be resolved it is probably some misconfiguration with your package manager.
