### ISSUE TITLE
per-service mixin example?

### ISSUE THREAD

**Issue by jnardone** [feathersjs/feathers#1684]
The docs are pretty light (and mostly refer to `uberproto`) around a per-service mixin.  Is there a simple example available (say I wanted to create an additional object and hook methods on top of the authentication service, as an example) - it's not 100% clear to me what type of object gets passed to `service.mixin(??)`

**Comment by daffl** [comment]
The preferred way to add functionality is extending the service classes, for the authentication service this is documented in the [authentication service customization section](https://docs.feathersjs.com/api/authentication/service.html#customization).

**Comment by jnardone** [comment]
In the more general case though, what's the pattern/use case for service mixins?  Or is there one?  Something that can't just be done with hooks because of object lifetimes etc.

**Comment by daffl** [comment]
Enabling hooks and events _was_ the use case for mixins. With ES6 classes being the standard now, Uberproto has become more of a legacy leftover. The next version (especially #932) is very likely to make the mixin (and other Uberproto) functionality obsolete.

**Comment by claustres** [comment]
Prior to ES6 classes mixins where used to emulate "static inheritance" although they are basically something like "dynamic inheritance". There are some use cases not covered by class inheritance, for instance we are used to change the service adapter based on a configuration, e.g. we use an in-memory service for tests and a DB service for app execution. In this case you don't know prior to execution what is the base class of your service. That's a reason why you could keep the mixin feature.

**Comment by homj** [comment]
I'm also strongly supporting to keep mixins. We built a set of libraries on top of feathers for internal use that all rely on this mixin feature.
E.g. one library adds logic to register and dispatch notifications (e.g. emails) based on service events, another one lets us define authorization / permissions... the list goes on.

All these features are independent form the service implementation, and this kind of independency from the implementation (e.g. with database adapters) has been at the core of feathers. Thus, removing the ability to add implementation-independent logic globally via mixins would contradict one of the core principles that make feathers so great.

So maybe instead of removing mixins, why not make it a more public api and promote its use?

**Comment by daffl** [comment]
Your examples sound exactly like what Feathers hooks are intended for though. `app.mixin` won't got away anyway. It's already basically just a callback that gets called whenever a service gets registered.

What will go away is the use of the custom ES5 inheritance wrapper [Uberproto](https://github.com/daffl/uberproto). You can add it yourself if you feel you really need it but there is a reason modern ES6 - and most libraries like React or VueJS - moved away from tacking on functionality outside of the inheritance chain.
