### ISSUE TITLE
Unified database adapters

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers#170]
Here is a list of all official supported database and ORM service adapters. Checked off adapters have been completely migrated to the common querying mechanism (see [feathers-service-tests](https://github.com/feathersjs/feathers-service-tests)), ES6 classes, promises and verified with working examples:

Standalone services:

- [x] [Memory](https://github.com/feathersjs/feathers-memory)
- [x] ~~[MongoDB](https://github.com/feathersjs/feathers-mongodb)~~ - we already have mongoose and waterline.
- [x] [NeDB](https://github.com/feathersjs/feathers-nedb)
- ~~[RethinkDB](https://github.com/feathersjs/feathers-rethinkdb)~~ - It's not ready yet and can be released later.

ORMs:

- [x] [Knex](https://github.com/feathersjs/feathers-knex)
- [x] [Sequelize](https://github.com/feathersjs/feathers-sequelize)
- [x] [Mongoose](https://github.com/feathersjs/feathers-mongoose)
- [x] [Waterline](https://github.com/feathersjs/feathers-waterline)

**Comment by daffl** [comment]
This is to keep track of the adapters where the released version and documentation has been verified:

- [ ] [Memory](https://github.com/feathersjs/feathers-memory)
- [ ] [MongoDB](https://github.com/feathersjs/feathers-mongodb)
- [ ] [Mongoose](https://github.com/feathersjs/feathers-mongoose)
- [ ] [NeDB](https://github.com/feathersjs/feathers-nedb)
- [ ] [Knex](https://github.com/feathersjs/feathers-knex)
- [ ] [MySQL](https://github.com/feathersjs/feathers-mysql)
- [ ] [PostgreSQL](https://github.com/feathersjs/feathers-postgresql)
- [ ] [SQLite](https://github.com/feathersjs/feathers-sqlite)

**Comment by marshallswain** [comment]
Do we want to add RethinkDB to this list?

**Comment by daffl** [comment]
Yes. I had a chat with @ekryski this week and we were thinking of supporting multiple ORMs (Waterline, Mongoose, Sequelize and Knex) instead of multiple specific database adapters. This would make it easier to maintain and give us a lot of databases plus things like GraphQL for free.
However, none of those seem to really support RethinkDB so we definitely need that adapter. What was the name of the RethinkDB ORM you mentioned?

**Comment by marshallswain** [comment]
Thinky

**Comment by daffl** [comment]
@marshallswain @ekryski I updated the list of the officially supported databases and ORM adapters, let me know if that makes sense.

I am also inclined of migrating everything to ES6 classes and use of Promises (Feathers supports services that return a Promise since v1 and it should probably also become the default for v2) right away. That way everything would be lined up for Feathers 2. The API would be mostly the same but it will break Uberproto's `.extend` which I think would be ok as long as it will be a respective new major release.

**Comment by marshallswain** [comment]
Looks good.  I love how many DBs we get with the ORMs.  This is a good move.

**Comment by ekryski** [comment]
Looks good. :+1: for the call to move to ORMs.

**Comment by ekryski** [comment]
I just pushed an update to [feathers-waterline](https://github.com/feathersjs/feathers-waterline). From my manual testing everything appears to be working but I'm unable to get our common test passing because of [Waterline's async initialization](https://github.com/feathersjs/feathers-waterline/blob/master/test/index.test.js#L45,L78).

Help getting tests to pass would be appreciated. :smile:

**Comment by ekryski** [comment]
Just updated [feathers-knex](https://github.com/feathersjs/feathers-knex). Making good progress. Hope to have mongoose done later today as well.

**Comment by ekryski** [comment]
Feathers-waterline is up to date and has been released. Woop Woop!

Just wrapping up the updates to feathers-mongoose.

**Comment by ekryski** [comment]
[feathers-mongoose](https://github.com/feathersjs/feathers-mongoose) v3.0.0 is now out and is up to date.

**Comment by ekryski** [comment]
[feathers-nedb](https://github.com/feathersjs/feathers-nedb) v2.0.0 is now published. It was brought up to date by PR https://github.com/feathersjs/feathers-nedb/pull/8.

**Comment by ekryski** [comment]
So because we already have [feathers-mongoose](https://github.com/feathersjs/feathers-mongoose) and [feathers-waterline](https://github.com/feathersjs/feathers-mongoose) and we've found that most people want to work with an ORM it doesn't really make sense to have yet another mongodb adapter. Plus the native adapter's API is very tough to work with.

It can follow after the 2.0 release if required but it shouldn't hold it up. I've created https://github.com/feathersjs/feathers-mongodb/issues/16 and https://github.com/feathersjs/feathers-mongodb/issues/17 to track that progress.
