### ISSUE TITLE
disallow('external') blocks the call when AuthenticationService call UserService internally

### ISSUE THREAD

**Issue by Albert-Gao** [feathersjs/feathers#1727]
## Reproduce
1. use feathers cli to create a new app (enable Auth)
1. `npm i feathers-hooks-common`
1. in `users.hooks.ts`
    - `import { disallow } from "feathers-hooks-common";`
    - add `disallow("external")` to `before.all`
1. Go to postman
1. create new user: POST /users
1. login: POST /authentication
1. Error: 

```json
{
    "name": "MethodNotAllowed",
    "message": "Provider 'rest' can not call 'get'. (disallow)",
    "code": 405,
    "className": "method-not-allowed",
    "errors": {}
}
```

## Expect:

1. login should work and AccessToken should be returned.

Since I am calling `/authentication`, any request from /auth to /users should consider non-external?

==================
### disallow source code:
https://github.com/feathersjs-ecosystem/feathers-hooks-common/blob/master/lib/services/disallow.js

This is the source code when start finding the user:

https://github.com/feathersjs/feathers/blob/f4331aa397fa58360283ed52b84bcc690b43f32c/packages/authentication-local/src/strategy.ts#L123

Is it because here we are omitting the provider? But I think it is being remove for some reason?

**Comment by daffl** [comment]
This is because the authentication service is returning the user using an external call. You could [customize](https://docs.feathersjs.com/api/authentication/jwt.html#customization) the methods how entities are retrieved (`getEntity`) but the better way is to just allow external access to the users service how it is already set up ([limit the query](https://github.com/feathersjs-ecosystem/feathers-authentication-hooks) for appropriate access).

**Comment by Albert-Gao** [comment]
That is a good repo! Thanks!
