### ISSUE TITLE
Update event is not fired on a specific value

### ISSUE THREAD

**Issue by wasd171** [feathersjs/feathers#173]
Hi!

Consider the following `Service`:

```
export default {
	counter: 3,

	get: function (id, params, callback) {
		callback(null, this.counter);
	},

	update: function (id, data, params, callback) {
		this.counter = data.counter;
		callback(null, this.counter);
	}
}
```

For some reason, setting this.counter to 0 does not fire `counter updated` event. All other values fire update event

**Comment by daffl** [comment]
While it is probably possible, sending non-object primitives values is somewhat *undefined behaviour* since there may be things that expect it to be an object (e.g. `updated` does not fire if the returned value is falsy, so any of `null`, `undefined`, `false`, `''` or `0`). It should work fine in every case when you return the counter as an object like this:

```js
export default {
    counter: 3,

    get: function (id, params, callback) {
        callback(null, { counter: this.counter });
    },

    update: function (id, data, params, callback) {
        this.counter = data.counter;
        callback(null, { counter: this.counter });
    }
}
```

**Comment by daffl** [comment]
I hope that makes sense. If it doesn't solve the problem, please reopen or submit an issue if you have any other questions.
