### ISSUE TITLE
Newly generated app with custom service won't start

### ISSUE THREAD

**Issue by robianmcd** [feathersjs/feathers#1774]
### Steps to reproduce

- Generate a new app with `feathers generate app`
- When asked if the "app uses authentication" enter `y`
- When asked "What kind of service is it?" select "A custom service"
- `npm install`
- `npm start`

### Expected behavior
The app should start

### Actual behavior
The app outputs the error:

```
C:\path\server\node_modules\@feathersjs\authentication\lib\service.js:131
                throw new Error(`The '${service}' service does not have an 'id' property and no 'entityId' option is set.`);
                ^

Error: The 'users' service does not have an 'id' property and no 'entityId' option is set.
    at Object.setup (C:\path\server\node_modules\@feathersjs\authentication\lib\service.js:131:23)
    at C:\path\server\node_modules\@feathersjs\feathers\lib\application.js:139:17
    at Array.forEach (<anonymous>)
    at Function.setup [as _super] (C:\path\server\node_modules\@feathersjs\feathers\lib\application.js:133:32)
    at Function.setup (C:\path\server\node_modules\@feathersjs\socketio\lib\index.js:70:30)
    at Function.newMethod [as setup] (C:\path\server\node_modules\uberproto\lib\proto.js:34:20)
    at Function.listen (C:\path\server\node_modules\@feathersjs\express\lib\index.js:63:12)
    at Function.newMethod (C:\path\server\node_modules\uberproto\lib\proto.js:34:20)
    at Function.listen (C:\path\server\node_modules\@feathersjs\socketio\lib\index.js:39:25)
    at Function.newMethod [as listen] (C:\path\server\node_modules\uberproto\lib\proto.js:34:20)
```

### System configuration

**Module versions**:
@feathersjs/cli@4.2.4

**NodeJS version**:
13.1.0

**Operating System**:
Windows 10

**Comment by J3m5** [comment]
This is because the custom user service is not configured and has no schema.
When you an other king of service, the feathers cli configure it correctly.

**Comment by robianmcd** [comment]
Ok well it would be nice if the cli had a working example of a custom service as it's not clear to me how to create one. If I just add `id='users'` to the custom service it works but I'm not sure why this is required and why it isn't set by the cli.

**Comment by daffl** [comment]
It needs what the Error message says. Since there is no way to know what the entity id field of a custom service is going to be it needs to either set `service.id` or [entityId in the authentication configuration](https://docs.feathersjs.com/api/authentication/service.html#configuration) to its id field name (usually `id` or `_id`).

**Comment by robianmcd** [comment]
Ah I see, so the `id` of a service is supposed to be the name of the field that identifies entities managed by the server. I wasn't getting that from the docs or the error message.

**Comment by daffl** [comment]
Pull requests with potential clarifications are always welcome. In general, for authentication it makes the most sense to extend a database adapter service and then customize it since the standard setup expects the users service to be compatible with the [database adapter common API and querying syntax](https://docs.feathersjs.com/api/databases/common.html).

**Comment by euglv** [comment]
It is unclear from the "database adapter common API and querying syntax" article what is the minimum required functionality to create `users` service manually.
