### ISSUE TITLE
Feathers Auth dosnt return all user fields

### ISSUE THREAD

**Issue by farhad-arjmand** [feathersjs/feathers#1845]
in local strategy feather return only email field
but user service have many fields
```

{
    "accessToken": "...",
    "authentication": {
        "strategy": "local"
    },
    "user": {
        "_id": "5e5522107a92d233ef05c81a",
        "email": "admin@admin.com",
        "createdAt": "2020-02-25T13:33:04.766Z",
        "updatedAt": "2020-02-25T13:33:04.766Z",
        "__v": 0
    }
}
```

**Comment by daffl** [comment]
Hi there! We are happy to help but we need more information about your problem.

### Error message

Are you getting an error message?

### Steps to reproduce

__The best way to get help is to share a GitHub repository or code snippet with the minimal setup to reproduce your issue.__

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:
