### ISSUE TITLE
Socket.io Client cannot connect to HTTPS.

### ISSUE THREAD

**Issue by feathers-wing** [feathersjs/feathers#1887]
Socket.io Client cannot connect to HTTPS.

server code:
```
const server_https = https.createServer({
    key: fs.readFileSync('cert/xxx.key'),
    cert: fs.readFileSync('cert/xxx.pem')
  }, app).listen(443);

  app.setup(server_https); 

  server_https.on('listening', () => {
    let connectDate = new Date().toLocaleTimeString();
    console.log(
      `start https://${host}:${port}`
    );
let ws = require('ws'); 
let server_ws = new ws.Server({ server: server_https }); 
server_ws.on('listening', () => {console.log(START wss://${host}:${port});});
```
Client
`const socket = io('https://xxxxx.com');`
Client report a timeout error.

so how I set up a https connection between the client and the server and ensure a real-time connection???

**Comment by daffl** [comment]
You only need what is [documented in the API](https://docs.feathersjs.com/api/express.html#https) , the code after `let ws = require('ws');` is not necessary and is probably why it doesn't work.

If your certificate is self-signed (for testing purposes) you also need `const socket = io('https://xxxxx.com', { rejectUnauthorized: false })` on the client.

**Comment by edwardsmarkf** [comment]
What happens if you run both https and websockets over port 443?  Also I believe you are missing the chaining cert.

On March 22, 2020, at 11:10 PM, feathers <notifications@github.com> wrote:

Socket.io Client cannot connect to HTTPS.

server code:

const server_https = https.createServer({ key: fs.readFileSync('cert/xxx.key'), cert: fs.readFileSync('cert/xxx.pem') }, app).listen(443); app.setup(server_https); server_https.on('listening', () => { let connectDate = new Date().toLocaleTimeString(); console.log( `start https://${host}:${port}` ); let ws = require('ws'); let server_ws = new ws.Server({ server: server_https }); server_ws.on('listening', () => {console.log(START wss://${host}:${port});}); 

Client
const socket = io('https://xxxxx.com');
Client report a timeout error.

so how I set up a https connection between the client and the server and ensure a real-time connection???

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/feathersjs/feathers/issues/1887">https://github.com/feathersjs/feathers/issues/1887</a>", "url": "<a href="https://github.com/feathersjs/feathers/issues/1887">https://github.com/feathersjs/feathers/issues/1887</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by feathers-wing** [comment]
I have set this up according to the documentation,  and have removed ws.
and the client has also added “rejectUnauthorized: false”

but now the problems repeatedly reported by the server are:
`Page not found {"type":"FeathersError","name":"NotFound","code":404,"className":"not-found","data":{"url":"/socket.io/?EIO=3&transport=websocket"},"errors":{}}`

I don't know what's wrong？

**Comment by feathers-wing** [comment]
server:
```
const app = require('./app');
const https = require('https');
const server_http = app.listen(port);

server_http.on('listening', () => {
  let connectDate = new Date().toLocaleTimeString();
  console.log(
    `start http://${host}:${port}`
  );
});

const server_https = https.createServer({
    key: fs.readFileSync('xxx.key'),
    cert: fs.readFileSync('xxx.pem')
  }, app).listen(443);

  app.setup(server_https); 

  server_https.on('listening', () => {
    console.log(
      `start https://${host}:433`
    );
  });
```

client vue app:
```
import io from 'socket.io-client'
import feathers from '@feathersjs/feathers'
import socketio from '@feathersjs/socketio-client'

import auth from '@feathersjs/authentication-client'

const socket = io('https://xxx.com:443', {
  transports: ['websocket'],
  rejectUnauthorized: false
})

const ing = feathers()
  .configure(socketio(socket, { timeout: 8000 }))
  .configure(auth({ storage: window.localStorage }))
```

now the problems repeatedly reported by the server are:
`Page not found {"type":"FeathersError","name":"NotFound","code":404,"className":"not-found","data":{"url":"/socket.io/?EIO=3&transport=websocket"},"errors":{}}`

**Comment by daffl** [comment]
You `src/index.js` should look like this:

```js
const https = require('https');

const logger = require('./logger');
const app = require('./app');
const port = app.get('port');

const server = https.createServer({
  key: fs.readFileSync('privatekey.pem'),
  cert: fs.readFileSync('certificate.pem')
}, app).listen(443);

// Call app.setup to initialize all services and SocketIO
app.setup(server);

process.on('unhandledRejection', (reason, p) =>
  logger.error('Unhandled Rejection at: Promise ', p, reason)
);

server.on('listening', () =>
  logger.info('Feathers application started on http://%s:%d', app.get('host'), port)
);
```

**Comment by edwardsmarkf** [comment]
const server = https.createServer({
  key: fs.readFileSync('privatekey.pem'),
  cert: fs.readFileSync('certificate.pem'),
  ca:   fs.readFileSync('ca-chain.pem')        /* required??  */
}, app).listen(443);

in order to pass test https://www.sslshopper.com/ssl-checker.html   i think
its required.


Thank you,

Mark Edwards

**Comment by feathers-wing** [comment]
thank you very much!

Maybe I didn't make myself clear. My server itself is correct, and the code you pasted is exactly the same. A small lock icon will also appear when accessing the service address with a browser. 

test https://www.sslshopper.com/ssl-checker.html ，I have Passed the SSL Checker test and got the all-green tick! 💯

My current problem is that once the client starts, the server will report an error! Would you please focus on my client code?

`import io from 'socket.io-client'
import feathers from '@feathersjs/feathers'
import socketio from '@feathersjs/socketio-client'

import auth from '@feathersjs/authentication-client'

const socket = io('https://xxx.com:443', {
  transports: ['websocket'],
  rejectUnauthorized: false
})

const client = feathers()
  .configure(socketio(socket, { timeout: 8000 }))
  .configure(auth({ storage: window.localStorage }))`

now the problems repeatedly reported by the server are:
`Page not found {"type":"FeathersError","name":"NotFound","code":404,"className":"not-found","data":{"url":"/socket.io/?EIO=3&transport=websocket"},"errors":{}}`

**Comment by edwardsmarkf** [comment]
Have you tried running the simplest socket.io examples from their website, and then carefully changing those examples to recreate the issue?  

From there, you could put your small code example on stack overflow.   I might even try running it myself.  😁

On March 25, 2020, at 7:30 AM, feathers <notifications@github.com> wrote:

thank you very much!

Maybe I didn't make myself clear. My server itself is correct, and the code you pasted is exactly the same. A small lock icon will also appear when accessing the service address with a browser.

test https://www.sslshopper.com/ssl-checker.html ，I have Passed the SSL Checker test and got the all-green tick! 💯

My current problem is that once the client starts, the server will report an error! Would you please focus on my client code?

`import io from 'socket.io-client'
import feathers from '@feathersjs/feathers'
import socketio from '@feathersjs/socketio-client'

import auth from '@feathersjs/authentication-client'

const socket = io('https://xxx.com:443', {
transports: ['websocket'],
rejectUnauthorized: false
})

const client = feathers()
.configure(socketio(socket, { timeout: 8000 }))
.configure(auth({ storage: window.localStorage }))`

now the problems repeatedly reported by the server are:
Page not found {"type":"FeathersError","name":"NotFound","code":404,"className":"not-found","data":{"url":"/socket.io/?EIO=3&transport=websocket"},"errors":{}}

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/feathersjs/feathers/issues/1887#issuecomment-603871673">https://github.com/feathersjs/feathers/issues/1887#issuecomment-603871673</a>", "url": "<a href="https://github.com/feathersjs/feathers/issues/1887#issuecomment-603871673">https://github.com/feathersjs/feathers/issues/1887#issuecomment-603871673</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by daffl** [comment]
The setup I shared works fine when I tested it with the [Feathers chat](https://github.com/feathersjs/feathers-chat) (although you temporarily have to accept the unsigned certificate in the browser). Your client side setup is fine, the error is coming from the server. Please share a _complete_ repository and the steps to reproduce your issue.

**Comment by feathers-wing** [comment]
Normally, I can connect to sockte,. Once I switch to https, I can't connect !!！

**Comment by feathers-wing** [comment]
my website is  :  https://open.ing-x.com , you can open and test, it is normal.

but IF my client change to https：
const socket = io('https://open.ing-x.com:443')

the server will repeatedly reported  are:
Page not found {"type":"FeathersError","name":"NotFound","code":404,"className":"not-found","data":{"url":"/socket.io/?EIO=3&transport=websocket"},"errors":{}}

**Comment by edwardsmarkf** [comment]
dumb question - have you tried just   `const socket = io();`  ?

Thank you,

Mark Edwards

**Comment by feathers-wing** [comment]
I found the problem because both http and https were enabled at the same time. If only one was started, it would be successful. So what should I do if I want to support both http and https ?

**Comment by daffl** [comment]
Use an [NginX proxy](https://github.com/nginx-proxy/nginx-proxy). All of this is usually already covered by your hosting provider (e.g. Heroku) or cloud platform (e.g. Kubernetes).
