### ISSUE TITLE
set context.statusCode didn't work in error hook

### ISSUE THREAD

**Issue by elixiao** [feathersjs/feathers#1900]
According to the [doc](https://docs.feathersjs.com/api/hooks.html#context-statuscode): 
> context.statusCode is a writeable, optional property that allows to override the standard HTTP status code that should be returned.

But it seems not work. Here is my code:

```js
export default {
  error: {
    all: [],
    find: [(ctx: any) => {
      ctx.statusCode = 401
      console.log('ctx.statusCode=', ctx.statusCode)
      return ctx
    }]
  }
}
```

The console output shows `ctx.statusCode= 401` but the response status code was not 401. How can I modify status code in error hook?

**Comment by daffl** [comment]
Throwing a [`NotAuthenticated` Feathers error](https://docs.feathersjs.com/api/errors.html) will set the right status code automatically.

**Comment by elixiao** [comment]
@daffl Can I change error status code in error hook?

**Comment by daffl** [comment]
You can throw a different error that has the status code you need or use your own [errorHandler middleware](https://docs.feathersjs.com/api/express.html#express-errorhandler). The default errorHandler middleware will currently always use the `error.code` (because it doesn't know about the hook `statusCode`).

**Comment by elixiao** [comment]
Yes, that's what I am looking for. Thank you very much. @daffl
