### ISSUE TITLE
feathers-localstorage adapter

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers#195]
Based on the code example in #193, a localStorage adapter would be awesome.  Do we want to use NeDB, since it has a [browser version](https://github.com/louischatriot/nedb#browser-version)?  Or should we use localForage to use better storage tech when available?

http://nolanlawson.com/2015/09/29/indexeddb-websql-localstorage-what-blocks-the-dom/

**Comment by daffl** [comment]
Might need some more research but I was thinking for now to maybe just extend [feathers-memory](https://github.com/feathersjs/feathers-memory/) with LocalStorage synching?

**Comment by ekryski** [comment]
Ya I would say for a first cut taking @daffl's suggestion. There is a chance we might be able to just make `feathers-nedb` isomorphic as well but I would say that is separate from localstorage.

**Comment by ahdinosaur** [comment]
@ekryski along that train of thought, i'd love if someone made a `feathers-level` using [levelup](https://www.npmjs.com/package/levelup) with [leveldown](https://www.npmjs.com/package/leveldown) (or [any other storage backend](https://github.com/Level/levelup/wiki/Modules#storage)) in node and [level-js](https://www.npmjs.com/package/level-js) in the browser.

**Comment by ekryski** [comment]
@ahdinosaur I created a new issue (#228) to track that.

**Comment by ekryski** [comment]
I'm actually working on this right now because I need it for authentication for react native. React Native uses [async storage](https://facebook.github.io/react-native/docs/asyncstorage.html) so we should able to write an adapter that will work for storing stuff in localstorage or async storage kind of like how [this works](https://github.com/thewei/react-native-store).

The good thing is we already have `feathers-memory` and like @daffl suggested we can probably just modify it to work with with local storage and async storage.

**Comment by ekryski** [comment]
Work has started in this repo: https://github.com/feathersjs/feathers-localstorage

**Comment by ekryski** [comment]
v0.1.0 was released yesterday. Any future issues should be created in that repo.
