### ISSUE TITLE
Is now fastify v3 a good candidate for using with feathers ?

### ISSUE THREAD

**Issue by mdartic** [feathersjs/feathers#2017]
This isn't an issue, but I post here, hoping feedback.

Related to this issue : https://github.com/feathersjs/feathers/issues/258
and here more precisely  https://github.com/feathersjs/feathers/issues/258#issuecomment-360046739

Fastify is now in v3, cf https://medium.com/@fastifyjs/fastify-v3-released-da4601d79a5
If I've well understood, there is a compatibility with Express middleware, cf https://github.com/fastify/fastify-express.

https://github.com/fastify/fastify/issues/1503

What I've understood from https://github.com/feathersjs/feathers/issues/258#issuecomment-360046739 was that Passport would be hard to be usable without Express.

Do you think now fastify could be a good option in replacement of Express, 
and do you know if it would be painful to adapt a FeathersJS-express application in a FeathersJS-fastify one ?

Thanks for your thoughts, and thanks for all this amazing stack.

**Comment by daffl** [comment]
I talked about this before with @lucamaraschi and technically, yes it is possible (and similar to what is done for Koa at https://github.com/feathersjs/feathers/tree/koa). Since it is not on the top of my personal priority list this would however either require someone interested and able to contribute the integration or willing to pay for it through a [sponsorship](https://github.com/sponsors/daffl) for me to do it.

**Comment by mdartic** [comment]
Understood, 

I don't "need it" absolutely for now, so Express is ok for me, for now.

If I encounter some performance issues, maybe I'll give it a try.
I'll need to go deeper in FeathersJS code to well understand what I'll have to do (like your Koa code) to make Fastify work.

**Comment by asamolion** [comment]
@mdartic any updates on this?

**Comment by mdartic** [comment]
Nope, don't even try to wire Fastify & Feathers ! 
Performance is ok for now in my project with Express.
I don't have sufficient time to try with fastify.
