### ISSUE TITLE
socket.io namespace support

### ISSUE THREAD

**Issue by wuyuanyi135** [feathersjs/feathers#206]
Hi,
I wonder if we will have support for the namespace in socket.io so that for the service `todo`:
```js
app.use('/todo',todoService)
```
The client will start the connection by
```js
io.connect('/todo')
```

Currently, I can only use `io.connect()` to connect, and use the namespace in event string to separate the events
```js
socket.emit('todo::find', 1, function(error, data) {

});
```

I don't know much about socket.io ( New to web develop). Will it be benefit to implement this?

**Comment by daffl** [comment]
The problem is that namespaces (rooms) are a Socket.io only functionality. [Primus](https://github.com/primus/primus) only supports rooms as a plugin which we haven't tested out yet (and I am not sure if it works for all libraries Primus supports).

If you prefer the usage to be a little more more abstracted, [feathers-client](https://github.com/feathersjs/feathers-client/) is a very small wrapper that does all those things for you already:

```js
var feathers = require('feathers-client');
var socket = io('http://todos.feathersjs.com');
var app = feathers()
  .configure(feathers.socketio(socket));

app.service('todo').find().then(function(data) {
  console.log(data);
});
```

**Comment by daffl** [comment]
As a side note, by using `feathers-client` (or `feathers/client` for 2.0), if Socket.io rooms are more performant (I think it is more of a convenience wrapper but we may have to do some research) we will add it without having to change anything in the usage.

**Comment by wuyuanyi135** [comment]
:+1:  
Thanks.
