### ISSUE TITLE
OpenID Authentication Integration

### ISSUE THREAD

**Issue by astralmedia** [feathersjs/feathers#2122]
Is it possible to integrate OpenID providers to the current AuthenticationStrategy flow? I have been spending weeks trying to research & get this working, but cant seem to crack it. I have read that it was possible...

I've tried directly integrating Passport even just to use their OpenID implementation, but can't spin too many more cycles on this without progress.

Thanks for any insight.

**Comment by daffl** [comment]
Instead of trying to do it yourself you should probably rely on [Auth0](https://auth0.com/) and [their OpenID](https://auth0.com/docs/protocols/openid-connect-protocol) integration. Auth0 integration with Feathers is [documented in the Cookbook](https://docs.feathersjs.com/cookbook/authentication/auth0.html).

Closing since it is a broad question without a lot of information.
