### ISSUE TITLE
Client Authentication for SSR Strategies?

### ISSUE THREAD

**Issue by RickEyre** [feathersjs/feathers#2139]
Is there any canonical documentation for this, or any ideas where to get started?

I was assuming I'd have to implement my own AuthenticationClient strategy.

**Comment by jeffborg** [comment]
Try this (I just copied paste our feathers client for SSR)

Couple of things to note
A) there are 2 feathers instances - the server one and the client one (on the server)
B) using JSON.stringify/parse to seperate the object from server to client
C) injecting provider: 'direct' so that auth hooks etc.. just work like normal
D) this is done on client side by setting app.defaultService which feathers will return for any service (ie sort of a proxy)

I tried using same feathers instance but couldn't get it working
On client side we just use feathers as per normal
Also your auth setup will need to use cookies etc

```typescript
import { Plugin } from '@nuxt/types'
import { ServiceMethods, Application, Service } from '@feathersjs/feathers'
import feathersServer from '@@/server/app'
import feathersFactory from '../feathers/index'
import { authenticationClient } from './feathers.common'

declare module '@feathersjs/feathers' {
  interface Application<ServiceTypes = {}> {
    defaultService(location: string): ServiceMethods<any>;
  }
}

class ServiceProxy<T = any> implements ServiceMethods<T> {
  private service: Service<T>

  constructor (name: string, feathers: Application) {
    this.service = feathers.service(name)
  }

  find (params?: import('@feathersjs/feathers').Params | undefined): Promise<T | T[] | import('@feathersjs/feathers').Paginated<T>> {
    return this.service.find({
      ...params,
      provider: 'direct'
    })
  }

  get (id: import('@feathersjs/feathers').Id, params?: import('@feathersjs/feathers').Params | undefined): Promise<T> {
    return this.service.get(id, {
      ...params,
      provider: 'direct'
    })
  }

  create (data: Partial<T> | Partial<T>[], params?: import('@feathersjs/feathers').Params | undefined): Promise<T | T[]> {
    return this.service.create(data, {
      ...params,
      provider: 'direct'
    })
  }

  update (id: string | number | null, data: T, params?: import('@feathersjs/feathers').Params | undefined): Promise<T | T[]> {
    return this.service.update(id, data, {
      ...params,
      provider: 'direct'
    })
  }

  patch (id: string | number | null, data: Partial<T>, params?: import('@feathersjs/feathers').Params | undefined): Promise<T | T[]> {
    return this.service.patch(id, data, {
      ...params,
      provider: 'direct'
    })
  }

  remove (id: string | number | null, params?: import('@feathersjs/feathers').Params | undefined): Promise<T | T[]> {
    return this.service.remove(id, {
      ...params,
      provider: 'direct'
    })
  }
}

const feathersInject: Plugin = (context, inject) => {
  const feathers = feathersFactory()
  inject('feathers', feathers)
  feathers.configure(authenticationClient(context))

  feathers.hooks({
    after: {
      all: [
        (context) => {
          // overload result if dispatch has been set
          if (context.dispatch) {
            context.result = context.dispatch
          }
        },
        (context) => {
          // rewrite the result to destroy stuff like dates etc...
          context.result = JSON.parse(JSON.stringify(context.result))
        }
      ]
    },
    error: {
      all: [
        (context) => {
          // rewrite the result to destroy stuff like dates etc...
          context.error = JSON.parse(JSON.stringify(context.error))
        }
      ]
    }
  })
  // configure up a fake defaultServce - basically direct proxy to server feathers
  feathers.configure((app) => {
    app.defaultService = (name) => {
      return new ServiceProxy(name, feathersServer)
    }
  })
  // const feathersClient = rest('/api')
  // feathers.configure(feathersClient.axios(axios))
}

export default feathersInject

```

**Comment by RickEyre** [comment]
@jeffborg thank you for your answer.

1) What does the `direct` provider do, I don't see this one in the docs. Is this a custom implemented provider type you built?
2) How have you made authentication client work on your server side when by default it expects `localStorage`, etc., to exist. Have you built your own storage provider?

**Comment by jeffborg** [comment]
@RickEyre Forgot about the other pieces, but  it wasn't too hard in the end.

1. So need to put some value in provider so that the hooks etc which do this `if (provider)` will think the request is external, any value would do, it's usually rest, socketio, primus etc.., maybe calling it ssr would be better but no hook actually checks the value of this, only for it's empty string or false, null undefined etc...
2. Authentication just works as documented when you override the storage no issues As there are 2 feathers instances, One for the client side of SSR, and the server instance (inside the same nodejs process), Hence all this proxy type thing to separate the 2. Client works as you would expect by putting stuff into the headers, and the server instance hooks work as you expect by reading the headers field. It's just that no http or socket io has happened here and we just called the methods directly.

Sorry about auth yes we did override the storage for feathers, we are using nuxt auth for our app, so basically at the end of the day you need to set and read from cookies. See the nuxt auth file https://github.com/nuxt-community/auth-module/blob/dev/src/core/storage.ts for what is going on.

```typescript
import { Context } from '@nuxt/types'
import { Storage } from '@feathersjs/authentication-client'
import { authentication } from '@feathersjs/client'

// all of this works on client and SSR mode
export const authenticationClient = (context: Context) => {
  return authentication({
    storage: storage(context)
  })
}

export const storage = (context: Context): Storage => ({
  getItem (key: string) {
    return Promise.resolve(context.$auth.$storage.getUniversal(key, true))
  },
  removeItem (key: string) {
    return Promise.resolve(context.$auth.$storage.removeUniversal(key))
  },
  setItem (key: string, value: any) {
    return Promise.resolve(context.$auth.$storage.setUniversal(key, value, true))
  }
})

// use the auth client
feathers.configure(authenticationClient(context))

```

There is 1 more step for the client side only we need to force auth for feathers
```
    // force auth info if coming from ssr - customise to fit your framework etc...
    if (context.store.state.auth.loggedIn && !feathers.get('authentiation')) {
      feathers.reAuthenticate() // auth the socket so future calls work.
    }

```

**Comment by RickEyre** [comment]
Awesome thanks!
