### ISSUE TITLE
Can't make Google Login to work

### ISSUE THREAD

**Issue by rondaniel00** [feathersjs/feathers#2174]
### Steps to reproduce
Follow the user tutorial for setting up the server and then follow the Google Strategy cookbook.
In addition, add the xommand in the client to authenticate through google strategy.

At the beginning I got an error message that the google strategy is not recognied. Then, when I added it to the config file, I got an error on the client sayimg timeout and on the server I had Promise exception.

I tried to update verwions for both client and server but results were the same.

Please try to reproduce and tomorrow I will post the exact error meaaages and screenshots.

@daffl

**Comment by edwardsmarkf** [comment]
Dumb question: what about using the feathersjs generator?  That works consistently with gmail, and every other one I tested.

On December 24, 2020, at 3:34 PM, Ron Daniel <notifications@github.com> wrote:

Steps to reproduce

Follow the user tutorial for setting up the server and then follow the Google Strategy cookbook.
In addition, add the xommand in the client to authenticate through google strategy.

At the beginning I got an error message that the google strategy is not recognied. Then, when I added it to the config file, I got an error on the client sayimg timeout and on the server I had Promise exception.

I tried to update verwions for both client and server but results were the same.

Please try to reproduce and tomorrow I will post the exact error meaaages and screenshots.

@daffl

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/feathersjs/feathers/issues/2174">https://github.com/feathersjs/feathers/issues/2174</a>", "url": "<a href="https://github.com/feathersjs/feathers/issues/2174">https://github.com/feathersjs/feathers/issues/2174</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by rondaniel00** [comment]
> Dumb question: what about using the feathersjs generator? That works consistently with gmail, and every other one I tested. On December 24, 2020, at 3:34 PM, Ron Daniel <notifications@github.com> wrote: Steps to reproduce Follow the user tutorial for setting up the server and then follow the Google Strategy cookbook. In addition, add the xommand in the client to authenticate through google strategy. At the beginning I got an error message that the google strategy is not recognied. Then, when I added it to the config file, I got an error on the client sayimg timeout and on the server I had Promise exception. I tried to update verwions for both client and server but results were the same. Please try to reproduce and tomorrow I will post the exact error meaaages and screenshots. @daffl — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.￼ [ { "@context": "<a href="[http://schema.org">http://schema.org</a](http://schema.org%22>http://schema.org</a)>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="#2174">https://github.com/feathersjs/feathers/issues/2174</a>", "url": "<a href="#2174">https://github.com/feathersjs/feathers/issues/2174</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="[https://github.com">https://github.com</a](https://github.com%22>https://github.com</a)>" } } ]

Hi, thanks for reaching out buddy :) I really tried everything. All versions are updated.
I generated the server via the CLI and also configured GOOGLE oauth as per the cookbook.
Also, I tried to create several clients as per this document
https://docs.feathersjs.com/api/client.html#node
and I get this error in the client
"Invalid authentication information (strategy not allowed in authStrategies"
Then i tried to edit


`"authentication": {
    "entity": "user",
    "service": "users",
    "secret": "ALNxkhLVaBtfhTtH3Nik/mVX9pY=",
    "authStrategies": [
      "jwt",
      "local"
    ]`
and put "google" within "authStrategies"
but then I got this error on the server 

"error: Unhandled Rejection at: Promise"
and on the client I got timeout error.

Please help.

**Comment by edwardsmarkf** [comment]
For fun, can you please try using Auth0 instead?

On December 25, 2020, at 5:29 AM, Ron Daniel <notifications@github.com> wrote:

Dumb question: what about using the feathersjs generator? That works consistently with gmail, and every other one I tested. On December 24, 2020, at 3:34 PM, Ron Daniel notifications@github.com wrote: Steps to reproduce Follow the user tutorial for setting up the server and then follow the Google Strategy cookbook. In addition, add the xommand in the client to authenticate through google strategy. At the beginning I got an error message that the google strategy is not recognied. Then, when I added it to the config file, I got an error on the client sayimg timeout and on the server I had Promise exception. I tried to update verwions for both client and server but results were the same. Please try to reproduce and tomorrow I will post the exact error meaaages and screenshots. @daffl — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.￼ { "@context": "http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#2174", "url": "#2174", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com</a](https://github.com%22>https://github.com</a)>" } } ]

Hi, thanks for reaching out buddy :) I really tried everything. All versions are updated.
I generated the server via the CLI and also configured GOOGLE oauth as per the cookbook.
Also, I tried to create several clients as per this document
https://docs.feathersjs.com/api/client.html#node
and I get this error in the client
"Invalid authentication information (strategy not allowed in authStrategies"
Then i tried to edit
` "authentication": {
"entity": "user",
"service": "users",
"secret": "ALNxkhLVaBtfhTtH3Nik/mVX9pY=",
"authStrategies": [
"jwt",
"local"

],` 

and put "google" within "authStrategies"
but then I got this error on the server

"error: Unhandled Rejection at: Promise"
and on the client I got timeout error.

Please help.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/feathersjs/feathers/issues/2174#issuecomment-751242810">https://github.com/feathersjs/feathers/issues/2174#issuecomment-751242810</a>", "url": "<a href="https://github.com/feathersjs/feathers/issues/2174#issuecomment-751242810">https://github.com/feathersjs/feathers/issues/2174#issuecomment-751242810</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by rondaniel00** [comment]
I didn't use OAUTH as needed. I should have used http://localhost:3030/oath/google to make the login and not client.authenticate method.

**Comment by ppulwey** [comment]
@rondaniel00 Had the same issue.
I tried to login with the strategy on client `await app.reAuthenticate({ strategy: "google" });`
But what actually is needed is: `await app.reAuthenticate();` without the strategy property.
