### ISSUE TITLE
RockDB support

### ISSUE THREAD

**Issue by rsklyar** [feathersjs/feathers#220]
any rockdb support ?

**Comment by daffl** [comment]
It does not look as if RocksDB has any official Node bindings (see https://github.com/facebook/rocksdb/issues/109#issuecomment-60676895) and the ones that are on NPM do not seem to be maintained.

Since it is build on LevelDB it may be possible to use it with [feathers-waterline](https://github.com/feathersjs/feathers-waterline) and [sails-leveldb](https://github.com/mbinot/sails-leveldb).

**Comment by daffl** [comment]
Closing. Feel free to comment if you have any other questions.
