### ISSUE TITLE
Errors not being translated to status codes.

### ISSUE THREAD

**Issue by scvnc** [feathersjs/feathers#221]
Take feathers-nedb `get` implementation for example:

    if(!doc) {
        throw new errors.NotFound(`No record found for id '${_id}'`);
    }

I can dig that.. but when it bubbles up to the HTTP layer it gives me a node stack trace along with a HTTP Status 500.  It seems like it would be better to have something to sniff out that this error should translate into a 404 response by default.

**Comment by daffl** [comment]
Did you use the [Feathers generator](https://github.com/feathersjs/generator-feathers)? It will add an [error handler middleware](https://github.com/feathersjs/generator-feathers/blob/master/generators/app/templates/static/src/middleware/error-handler.js) that sets the correct status code (errors come with their status code). Otherwise you will have to provide your own Express error handler. The one we are usually using looks like this:

```js
const errors = require('feathers-errors');

app.use(function(error, req, res, next) {
  if (typeof error === 'string') {
    error = new errors.GeneralError(error);
  } else if ( !(error instanceof errors.FeathersError) ) {
    let oldError = error;
    error = new errors.GeneralError(oldError.message, {errors: oldError.errors});

    if (oldError.stack) {
      error.stack = oldError.stack;
    }
  }

  const code = !isNaN( parseInt(error.code, 10) ) ? parseInt(error.code, 10) : 500;

  // Don't show stack trace if it is a 404 error
  if (code === 404) {
    error.stack = null;
  }

  res.status(code);

  res.format({
    'text/html': function() {
      const file = code === 404 ? '404.html' : '500.html';
      res.sendFile(path.join(req.app.get('public'), file));
    },

    'application/json': function () {
      let output = Object.assign({}, error.toJSON());

      if (req.app.settings.env === 'production') {
        delete output.stack;
      }

      res.json(output);
    }
  });
})
``

**Comment by ekryski** [comment]
Ya I'm running into something with the error handler in the generator. I had thought I fixed it already but I'll take a look again this afternoon.

**Comment by scvnc** [comment]
No I didn't use the generator, but cool-- I'll go down the path of writing my own middleware.  I had some impression that there would be some basic handling of it built-in considering that the feathers-errors repo lists many errors alongside the correlating HTTP code. Might be a nice topic for the docs. 

Thanks!

**Comment by daffl** [comment]
Yep, I'm just adding it to http://docs.feathersjs.com/middleware/express.html.

**Comment by ekryski** [comment]
@scvnc we initially did have a bundled error handler and may decide to bring it back, but the issue was that people ended up wanting to have all sorts of options and it was assuming a lot about your set up. It is much easier to customize the middleware that comes with the a generated app than a sub module.

**Comment by ekryski** [comment]
I made some updates to the error handler that comes with the generated app and while I was in there I verified that the errors are being returned correctly.
