### ISSUE TITLE
Suggestion: resultResolver should not resolve properties if they are not present in $select when $select is specified

### ISSUE THREAD

**Issue by idaho** [feathersjs/feathers#2595]
Currently all properties defined in resultResolver are resolved. Even if we do not explicitly specify them in $select.

As an example:
In a service a field exists, not in the database, but is calculated in the resultResolver. If we now query this service and select only some fields via $select and this field is not included, it is currently resolved and is thus unintentionally in the result. Unfortunately it is currently not possible to access `context.params.query.$select` in the resolver function, since it no longer exists at this point. Apart from this, an additional unnecessary function call is made here.

Disadvantage is of course at this point that this field would have to be filtered out in the service with the database query if the field is however explicitly selected with $select.

**Comment by DaddyWarbucks** [comment]
Something else to consider here are resolvers' "dependencies". For example,

```js
resolve({
  properties: {
    initials: function (value, object, context) {
      // Uh oh...we didn't $select author so we can't get initials
      return object.author.name
        .match(/(\b\S)?/g)
        .join('')
        .toUpperCase();
    }
  }
});

app.service('posts').find({ query: { $select: ['initials'] } })
``` 

When resolvers depend on some other property, using `$select` can cause that depended on property to not be present and cause errors.

I am not sure `feathers-schema` could/should solve this. The `$select` keyword has different effects depending on the underlying database adapter, and on some database adapters `$select` can actually be an object or even an array of arrays. And it is common to "extend" the query with other keywords that may clash with this, for example I have used a `$pick` and `$omit` keyword to add more functionality to what properties are returned. IMO its best to leave `feathers-schema` core out of this, but offer some examples or helper functions to handle it.

I have previously solved this in two ways. Note both of these are pseudo code because I have solved them with other resolvers, but the concept is the same. So I just whipped together these two quick examples, but they are untested.

1 - A custom hook that plucks off only resolvers in the `$select` array. Note this does not solve the "dependencies" problem mentioned above.
```js
const resolve = (context) => {
  const { query } = context.params;
  if (!query || !query.$select) {
    return resolveResult(schema)(context);
  }

  // Get the resolver properties that are in $select
  // Note union is pseudo code
  const properties = union(query.$select, schema.properties);

  // Create a new schema with only the props in $select
  // Note pluck is pseudo code
  const selectedSchema = pluck(schema, properties);

  return resolveResult(selectedSchema)(context);
};
```

2 - Create a helper function that is used in each resolver
```js
resolve({
  properties: {
    initials: function (value, object, context) {
      if (
        !isResolveable({
          key: 'initials',
          context,
          object,
          dependencies: ['user']
        })
      ) {
        return;
        // or maybe you want to throw an error
        // throw new Error('Cannot resolve "initials"')
      }

      return object.user.name
        .match(/(\b\S)?/g)
        .join('')
        .toUpperCase();
    }
  }
});

const isResolveable = ({ key, context, dependencies, object }) => {
  let selectable = true;
  let dependable = true;

  if (context.params.query.$select) {
    selectable = context.params.query.$select.includes(key);
  }

  if (dependencies) {
    dependable = dependencies.every((key) => object[key]);
  }

  return selectable && dependable;
};
```

**Comment by joezappie** [comment]
While basing a resolver properties exclusion list on $select is probably best implemented independently, I think having a generic mechanism built into resolvers to include/exclude what properties to run would be handy for many. In your example you have the pseudo code for `pluck` which I think is where I'd draw the line for what resolvers should handle. From this, if you wanted to base it on $select you would just write your hook to generate the inclusion/exclusion list based on that.

In some of the Dove documentation, there is one mention of the keyword `$resolve` used. Not sure if this is actually implemented or left to userland at the moment. I'm guessing the thought behind that though is similar to pluck where you'd provide it an array of what properties to run.

https://dove.docs.feathersjs.com/api/schema/resolvers.html#result-resolvers

Adding a bunch of logic into every property to check if it should be run seems like something that should just be provided in the API in my opinion.
