### ISSUE TITLE
Error handling: Pass stuff to'em.

### ISSUE THREAD

**Issue by IngwiePhoenix** [feathersjs/feathers#266]
Imagine the following: You write a middleware to request a remote system to generate a response, and it sends an error. That error might contain valuable information, but you just want to pass it forward to the standard, all-round error handler.

How to do that? All that I can see is static HTML files being used. But in fact, I am using PHP under the hood in my project and I want to drop some of the error messages into my view, to customize it a bit.

Would it be possible to actually use a callback instead of a string and have that execute instead of plain sending the file?

**Comment by daffl** [comment]
If you request JSON you get the fully serialized error. To add additional data to that error, you can [pass it to the feathers-errors instances](http://docs.feathersjs.com/middleware/error-handling.html#featherserror-api).

The static HTML pages do not render any error data because we didn't want to assume what view engine you were using (if it is an API only server you also usually don't need to send detailed errors to the browser). If you want to render your own error pages with more error information you can use Express and its [custom error handler](http://expressjs.com/en/guide/error-handling.html) instead of the `feathers-errors/handler`.

**Comment by ekryski** [comment]
@IngwiePhoenix ya you basically just use your own view engine and your own custom express error handler. You can pass any additional data to a FeathersError just as an object. I'm updating the error-handling docs with the Errors API and a section on rendering your own templated error pages.

**Comment by IngwiePhoenix** [comment]
@ekryski Cool, that'll be very helpful!

@daffl Express' error handling actually is creeping me out a little. The way I have learned about it is that at the very, very end of all routes, one has to create a middleware with four arguments. This always confused me really good. Error handling is usually the smallest and most untouched part, so I wanted to define it at the top and leave it there. That is why I thought Feathers' error handler would help me on that, as it appearently would let me define my error settings even at the top. Oh well - Ill see what example @ekryski will put together and go from there :)

**Comment by IngwiePhoenix** [comment]
Actually nevermind. I oversaw that before the example it read int he comments that it had to be set up as the last one as well.

Well, that basically brings me back to square one :). But thank you anyway!

**Comment by ekryski** [comment]
@IngwiePhoenix I think you brought up something valuable, in being able to pass a custom formatter. I've created an issue for that. https://github.com/feathersjs/feathers-errors/issues/32.

Why is it a problem that Express and Feathers want your error handler to be last?
