### ISSUE TITLE
new CLI bugs

### ISSUE THREAD

**Issue by mrfrase3** [feathersjs/feathers#2679]
Just using the new cli, will post my issues here:

- [ ] typescript is required as a global dep, trying to run the cli without it borks it
- [ ] Yarn option was ignored and deps were installed with npm instead, creating a package-lock

**Comment by daffl** [comment]
How does it bork without the TypeScript dependency? I just checked and I don't have it installed locally on the Linux or Mac machine I tested this on.

**Comment by mrfrase3** [comment]
I'm running on node 14 if that makes a difference.

I'm finding `feathers g` will just exit without an error, `feathers generate` still works.

I found the local auth strategy is being defined on incorrect white spacing.

![image](https://user-images.githubusercontent.com/3320430/176458508-f27ea47a-f900-468b-8b9a-4aae5efa1971.png)

Should googleId, facebookId, twitterId, etc be treated like a password field by default? At the very least, it would be nice to have a default resolver that blocks it from being set when context.provider is set.

The general lack of semicolons and end commas is driving me crazy...

It would be nice if there was a remove and/or rename command, that deleted/renamed a service. I find if I name something stupidly, it can be a pain to wipe/correct.

The option to select "setup dotenv" would be nice, and it sets up the `custom-environment-variables.json` and `.env` file

I think it might be a good idea to add the `title` and `description` fields to the schema properties generated, as it's good practice to document your schema and to make people aware that they can.

**Comment by daffl** [comment]
All good suggestions, here are the things that I'll try and address:

- [ ] The `feathers g` alias currently doesn't exist but I also don't like that it just exits with nothing so will definitely add a nicer help screen
- [x] oAuth provider support definitely needs to be improved - the actual integration for Koa is the last actual code piece missing for this release :neutral_face: 
- [x] For formatting, I actually already started working on supporting PrettierJS. If you have a local configuration (that e.g. uses semicolons or tailing commas), it will use that to format any source files that are generated or injected (which should also fix whitespace issues).
- [x] I think a `custom-environment-variables.json` should be generated either way but we are also planning on adding additional generator commands and `feathers generate dotenv` is a good idea

**Comment by FossPrime** [comment]
The yarn support could be implemented by making all NPM install calls with --no-package-lock. I may have yarn installed globally, but need/prefer to use turbo, pnpm or an older/newer NPM. For instance, the official container images often run 1 major version behind on NPM for the same Node version.

MrFrase I used semicolons most of my life, but https://slides.com/evanyou/semicolons converted me. I now look at them as useless extra clutter. It's only really a problem in self executing functions, which are trivial to avoid.

They also make the code less i18n, as many layouts don't prioritize them specially on mobile. I code on my phone for fun, but lots of folk in India/Africa/Apac only have a good phone as their main computer, not only due to the cost, but also blackouts, lack of sim cards and the cost of powering them.

In the list of state of JS libraries with S or A class developer satisfaction, I could only find two that used semicolons, out of 19. One was because the developers primarily used Go and Rust, the other is feature complete and not maintained. Feathers is not a legacy library, feathers is well maintained, **feathers should join the ranks of the good Js libraries and drop the semi**
