### ISSUE TITLE
missing extraHeaders

### ISSUE THREAD

**Issue by joacub** [feathersjs/feathers#2680]
socket client is missing extraHeaders param, seems like is overwriting deleting them.

VErsion of feathers: dove

**Comment by daffl** [comment]
The `extraHeaders` has to be passed when instantiating the Socket.io client connection (like in https://dove.feathersjs.com/api/client/socketio.html#authentication). The Feathers client does not use that setting.

**Comment by joacub** [comment]
that does not work sir, ido that and still not sending that in the request

**Comment by daffl** [comment]
We are happy to help but we need more information about your problem.

### Error message

Are you getting an error message?

### Steps to reproduce

__The best way to get help is to share a GitHub repository or code snippet with the minimal setup to reproduce your issue.__

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:
