### ISSUE TITLE
Recommendation for production deployment environment of feathers

### ISSUE THREAD

**Issue by takaaptech** [feathersjs/feathers#274]
Hi,
After develop api server using feathers, now i want to deploy app to vultr VPS with:
- CPU:	2 vCore
- Ram:	2048 MB
- OS:	CentOS 7 x64

Would you please recommend what i need to install:
- version of nodejs
- version of npm
- how to update code (via direct upload or using git)
- what is recommend command to start application, should i using pm2?

I know this question not so relate to feathers framework but i just think it is awesome if some one can share, that make feathers more strong and strong.
I just a newbie so please anyone have experience with real production environment show some tips and some setup profile.

Thank so much!

**Comment by kulakowka** [comment]
i'm using pm2 for production. It works fine. It have deployment system from the box.

**Comment by takaaptech** [comment]
Hi @kulakowka, what is version of nodejs and npm on your server? And what is command to start feathers using pm2? Do you need to create systemd?
Thank so much for the info!

**Comment by kulakowka** [comment]
Feathers are run like any other node.js application with pm2. 

PM2 has a [detailed documentation](https://keymetrics.io/2014/06/25/ecosystem-json-deploy-and-iterate-faster/). There are answers to all your questions.

**Comment by ekryski** [comment]
@takaaptech that's a really loaded question. It depends on how much traffic you have, what you are doing with your server, whether you are planning on scaling by creating a cluster.

To give you a general sense though, if you don't have a bunch of blocking code (ie. lot's of processing in memory or synchronous calls) you should be able to handle 1,000-10,000 simultaneous connections.

For deploying, personally I use CodeShip when I put stuff into production so that I have a continuous integration server running my tests. I also use Digital Ocean, AWS or Heroku for a lot of my hosting.

I would go with nodejs 5.x if you can. npm shouldn't matter too much.

**Comment by takaaptech** [comment]
Hi,
Thank you so much for nice hints!

**Comment by dhamaniasad** [comment]
I know this is a closed issue, but I would really appreciate some numbers on how many connections can be supported, some benchmarks basically. @ekryski.

**Comment by alnour-altegani** [comment]
any tool or package to benchmark nodejs performance like "apache benchmarking tool" ?

**Comment by anjmao** [comment]
@ghost your best friend is https://github.com/wg/wrk
