### ISSUE TITLE
What is the differences?

### ISSUE THREAD

**Issue by qiaoyan** [feathersjs/feathers#278]
Hi, I am moving from meteor. Just curious what is the differences from this acticle? thanks.
http://sahatyalkabov.com/create-a-character-voting-app-using-react-nodejs-mongodb-and-socketio/

**Comment by ekryski** [comment]
Hey @qiaoyan I didn't read the whole thing. That article is pretty lengthy. You can find the differences between Feathers and others [right here](http://docs.feathersjs.com/why/vs/readme.html). Feature wise they're pretty similar.

**Comment by daffl** [comment]
I didn't read the whole article either but what Feathers does most importantly is take a lot of the boilerplate out of setting up what is described there. @ekryski Already pointed out the documentation on the difference between Feathers and Meteor and how it leverages Express + Socket.io.

Creating a simple chat API with MongoDB, Feathers and React only takes 6 steps so I think it is also worth checking out our guide at http://docs.feathersjs.com/getting-started/readme.html.

I am going to close this issue because I think we linked all the resources necessary to answer this question but if you read up on them and want to know anything else, feel free to open another one.

**Comment by qiaoyan** [comment]
Hi ekryski and daffl, this answered my question,  which I was not sure before. That reduce many code and mistake chances. Thanks.
--------
what Feathers does most importantly is take a lot of the boilerplate out of setting up what is described there.
