### ISSUE TITLE
app.use('/location', service) vs app.service('/location', service)

### ISSUE THREAD

**Issue by farwayer** [feathersjs/feathers#287]
For now `service()` makes two different things: getting and registering service. It makes more hard to understand core API. We already have `use()` function for registering service. In my opinion one function must make one thing and one thing must be done in one way to make API more consistence and code more clear. Maybe it will be better to move registering service in `use()` only in one of next major release?

**Comment by corymsmith** [comment]
@farwayer use() and service() are two completely separate functions:
```
// Register the service
app.use('location', service);   
```

```
// Fetches the service to use somewhere else in your app
app.service('location')
```

**Comment by farwayer** [comment]
You are not right. We can register service with `app.service()` also. This is described in docs and realized in code. We need to get out this functionality from `service()` function.

**Comment by corymsmith** [comment]
@farwayer Can you send over the page in the docs where you see that?

**Comment by marshallswain** [comment]
@farwayer, Use the `service` method for services.  If you see other places where we're using `use` for a service, that should probably be changed in the documentation to avoid confusion, so please point it out.  The `use` method is meant for initializing plugins.

That said, if you're only using `app.service` to deal with services, there's no confusion and the API is the same as that of any getter/setter.

`app.service('/location', service)` to set.
`app.service('/location')` to get.

**Comment by marshallswain** [comment]
Actually, regarding plugins, I'm confusing `app.use` with `app.configure`, so never mind on that part.

**Comment by marshallswain** [comment]
And... it's all over the docs.  I agree that this is confusing.  Maybe I created that standard for myself, so I'll do some more checking.

**Comment by farwayer** [comment]
Thank you for response but featcher generator use `use()` function for registering service. Also some internal services (authentication for ex.) use it.

**Comment by corymsmith** [comment]
The way its done in the generator is the recommended way. 

Registering a service should be done with use() and service() should be used for fetching a service as its shown in the docs.

I'll let @ekryski or @daffl chime in if I'm incorrect :)

**Comment by farwayer** [comment]
That is what I meant: no one know how is right :smile:

**Comment by marshallswain** [comment]
Well, it's interesting to me that it's all over the docs this way.  :)  I remember originally using `app.service` to register services and `app.lookup` to retrieve references to them, but then we did away with `lookup` and merged its functionality into `service`.  `use` always worked to register services, but I guess as a personal preferences, I used `service` to differentiate between registering a service and a middleware.  I can see in the code that `use` calls `service` internally, which is good, because we want to pass middleware to the providers.  imo, all we need to do to clear up the potential for confusion is better explain the service method in the docs.  I don't think we need to change all cases of `use` to into `service`, instead.

**Comment by farwayer** [comment]
But if we need to add middleware must we use `use()`? Too many functions (`configure`, `use` and `service`) for basic things. It will confuse peoples. And it is `use()` everywhere in docs.

**Comment by marshallswain** [comment]
Well, `use` is around as part of the Express roots.  I don't think people will be confused if `service` is documented as both a getter and setter, but we stick to `use` in the docs.

**Comment by daffl** [comment]
`app.use` is an Express thing and will work for both to register a service if you pass a service object and for Express middleware if you pass a middleware function. I don't think we are using `app.service` anywhere in the documentation to register a new service except for mentioning that it is possible in the API docs for that method.

This is very likely to change for the next major version in #258 because not all frameworks have a `use` method but I think it should stay this way until then.

**Comment by farwayer** [comment]
Thanks for discussion guys! It is very important to keep things simple. For now `use()` trying to 'understand' did caller pass service or express middleware. It can be error prone.

**Comment by daffl** [comment]
That is true (see #285) which definitely needs a better error message. I think changing it to `app.service` consistently is a good suggestion but it shouldn't be done until the next major version (3.0) because otherwise it will make things even more confusing. We can take the documentation of  `app.service(name, service)` out of the API docs for now if it is causing issues.
