### ISSUE TITLE
OAuth Redirect Url

### ISSUE THREAD

**Issue by howlettt** [feathersjs/feathers#2990]
### Steps to reproduce

1. Configure a OAuth provider like [Google](https://feathersjs.com/cookbook/authentication/google.html) in the api (reproduced with Google & Microsoft)
2. Create a "Login Using Google" button that links to /oauth/google on a client website
3. Run the client website
4. Click the "Login Using Google" button
5. Login to your Google account
6. User is redirected back to the api which authenticates the user
7. Api then tries to redirect to https://accounts.google.com/ which results in the error `Referer "https://accounts.google.com/" is not allowed.`

### Expected behavior

Api should redirect back to the client website which triggered the login via a "Login Using Google" button

### Actual behavior

Api tries to redirect to https://accounts.google.com/

### System configuration

Feathers version: 5.0.0-pre.35

### Workaround
I'm able to workaround this by clearing the `referer` in a custom OAuth strategy, the api then uses the first url in the `origins` list in the configuration as the redirect url
```
class OAuthRefererStrategy extends OAuthStrategy {
  async getRedirect(
    data: AuthenticationResult | Error,
    params?: AuthenticationParams
  ): Promise<string | null> {
    if (params?.headers?.referer) {
      params.headers.referer = undefined;
    }
    return super.getRedirect(data, params);
  }
}
```

**Comment by daffl** [comment]
It looks like we need to store the original referrer (if it is set) when the flow gets started and use that since otherwise we will get the referrer from the provider.

**Comment by cciocov** [comment]
Hey @daffl 

The fix to this issue (i.e.: storing all headers in the session) introduces a new issue, where the session cookie becomes too big and breaks the auth flow. This happens in at least 2 scenarios:
1. The app sets other cookies (which will be part of the headers when the auth flow starts), which when encoded in the session cookie go past the cookie size limit
2. The auth flow is initiated multiple times, in which case, the session cookie keeps getting bigger and bigger (as the headers contain the session cookie, and we put the headers in the cookie)

Since we only need the referrer for the oauth logic, I suggest we only store that header instead of all of them.

**Comment by daffl** [comment]
Can you create a new issue for this?
