### ISSUE TITLE
Route arguments are not passed from client to server

### ISSUE THREAD

**Issue by mrpatiwi** [feathersjs/feathers#304]
I'm not able to pass route arguments (`/comments/:commentId/likes`) from client side feathers app.
Works perfectly from serverside.

---

Dependencies

``` sh
npm install body-parser feathers feathers-authentication feathers-hooks feathers-memory feathers-rest feathers-socketio socket.io-client
```

Code

``` js
'use strict';

const assert = require('assert');
const host = 'http://localhost:3030';

process.on('unhandledRejection', (reason, p) => {
  console.log("Unhandled Rejection at: Promise ", p, " reason: ", reason);
});

// Server
const feathers = require('feathers');
const socketio = require('feathers-socketio');
const hooks = require('feathers-hooks');
const bodyParser = require('body-parser');
const rest = require('feathers-rest');

const server = feathers()
  .configure(hooks())
  .configure(rest())
  .configure(socketio())
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))

server.use('/comments/:commentId/likes', {
  find: function(params) {
    // undefined when calling from client
    const commentId = params.commentId
    return Promise.resolve(commentId);
  }
});

const running = server.listen(3030);
running.on('listening', () => {
  console.log('Feathers application started');

  // Client
  const feathers = require('feathers/client')
  const socketio = require('feathers-socketio/client');
  const io = require('socket.io-client');

  const socket = io(host);
  const client = feathers()
    .configure(hooks())
    .configure(socketio(socket))

  server.service('/comments/:commentId/likes').find({ commentId: 1 }).then(id => {
    console.log('server:', id);
    assert.ok(id);
  });

  client.service('/comments/:commentId/likes').find({ commentId: 1 }).then(id => {
    console.log('client:', id);
    assert.ok(id);
  });
});
```

Output

``` text
Feathers application started
server: 1
client: null
Unhandled Rejection at: Promise  Promise {
  _c: [],
  _a: [],
  _s: 2,
  _d: true,
  _v:
   { [AssertionError: null == true]
     name: 'AssertionError',
     actual: null,
     expected: true,
     operator: '==',
     message: 'null == true',
     generatedMessage: true },
  _h: 0,
  _n: false }  reason:  { [AssertionError: null == true]
  name: 'AssertionError',
  actual: null,
  expected: true,
  operator: '==',
  message: 'null == true',
  generatedMessage: true }
```

**Comment by daffl** [comment]
So the problem is that SocketIO parameters only pass `params.query` between the client and the server.
Initially you were able to send all params via SocketIO but it was a big security issue because a client user might've been able to e.g. overwrite `params.sequelize` and send options directly to the database.

After thinking about this a little more, one way I came up with was to pass those options is via another special property, probably `params.query.$feathers` and then set them on `params` if the properties are a part of the service name (`:commentId` in this case).

**Comment by ekryski** [comment]
@daffl that sounds good. Being critical, part of me is wondering if we'd be (or we are already) making a mistake passing non query params inside `params.query`. Maybe we should just be passing the whole `params` object to the server. It makes a bit more sense really because that is what gets passed around on the server side.

However, I think there was a reason we decided not to do that. I just can't remember... do you? It would be more of a breaking change though which sucks.

**Comment by daffl** [comment]
> Initially you were able to send all params via SocketIO but it was a big security issue because a client user might've been able to e.g. overwrite `params.sequelize` and send options directly to the database.

**Comment by daffl** [comment]
That was the problem. Worst case is you could e.g. set `params.user` on an unauthenticated socket and just make requests that way or potentially even change things in the database directly.

**Comment by ekryski** [comment]
Right. My bad.

**Comment by ekryski** [comment]
Looking at @mrpatiwi's example again I don't know if we need to do anything to solve his problem. He's not even using the route param actually. If you pass the `commentId` in the query then you can just grab it. You can achieve the correct thing by simply doing this:

```js
'use strict';

const assert = require('assert');
const host = 'http://localhost:3030';

process.on('unhandledRejection', (reason, p) => {
  console.log("Unhandled Rejection at: Promise ", p, " reason: ", reason);
});

// Server
const feathers = require('feathers');
const socketio = require('feathers-socketio');
const hooks = require('feathers-hooks');
const bodyParser = require('body-parser');
const rest = require('feathers-rest');

const server = feathers()
  .configure(hooks())
  .configure(rest())
  .configure(socketio())
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))

server.use('/comments/:commentId/likes', {
  find: function(params) {
    // undefined when calling from client
    const commentId = params.query.commentId
    return Promise.resolve(commentId);
  }
});

const running = server.listen(3030);
running.on('listening', () => {
  console.log('Feathers application started');

  // Client
  const feathers = require('feathers/client')
  const socketio = require('feathers-socketio/client');
  const io = require('socket.io-client');

  const socket = io(host);
  const client = feathers()
    .configure(hooks())
    .configure(socketio(socket))

  server.service('/comments/:commentId/likes').find({ query: { commentId: 1 } }).then(id => {
    console.log('server:', id);
    assert.ok(id);
  });

  client.service('/comments/:commentId/likes').find({ query: { commentId: 1 } }).then(id => {
    console.log('client:', id);
    assert.ok(id);
  });
});
```

**Comment by mrpatiwi** [comment]
@ekryski good idea!

Maybe that should be mentioned on the last example of: http://docs.feathersjs.com/middleware/routing.html#nested-routes

**Comment by ekryski** [comment]
@mrpatiwi yeah for sure! I was just chatting with @daffl. We're not sure if we screwed up something by mapping the route params to the `params` object instead of `params.query`. I'm just about wrapped up the many-to-many example for sequelize. Have been trying out a few different ways to model this stuff to see which is the most "feathers-y" way.

**Comment by daffl** [comment]
So one easy way to solve this right away would be to add a hook that maps the param to the query:

```
server.service('/comments/:commentId/likes').before(hook => {
  hook.params.query.commentId = hook.params.commentId;
});
```

Now you can just use `params.query` as with everything else.

**Comment by juodumas** [comment]
Was having a similar discussion with @daffl on Slack.

Currently it is impossible to pass parameters from a client to an `after` hook using the `find()` method and without an intermediate `before` hook. A good example is in the docs: https://github.com/feathersjs/feathers-docs/blob/master/hooks/examples.md#fetching-related-items. If we change this example to use `find()` instead of `get()`, it won't work because the query will search for documents with `{related: true}` and `hook.result` will be empty in the `after` hook. A workaround would be to set `hook.params.related = hook.params.query.related; delete hook.params.query.related` in a `before` hook, but I feel that a more general solution is needed.

Possibilities:
1. Send the whole `params` object, but namespace it server side, e.g. `hooks.params.client`.
2. Do not barf on unknown special properties in `params.query`, e.g. `params.query.$view`.
3. Use a special `params.query.$feathers` for non-query parameters.
4. Send `params.client` in addition `params.query` to the server.

**Comment by ekryski** [comment]
@juodumas I like a lot of those suggestions. I guess we'll need to discuss with the @feathersjs/core-team because that would involve some breaking changes across many repos. If we're going to do it. The Buzzard release would be the time to do it.

**Comment by marshallswain** [comment]
I like the idea of passing the entire object to the server where they become `params.client`.  So, the first argument become `params.query`, and the second become `params.client`.

**Comment by daffl** [comment]
That won't work very well for HTTP URLs unless we introduce a major breaking change and use `query` as the where clause, remove the `$limit`, `$skip` and `$select` as special parameters and move them to the top level:

```js
app.service('todos').find({
  limit: 10,
  skip: 10,
  query: {
    completed: true,
    created: { $gt: 'week' }
  }
});
```

HTTP:

`limit=10&skip=10&query[completed]=true`.

**Comment by marshallswain** [comment]
I don't think we have to move the special query params.  They're safe where they are.  What I'm proposing is something like this:  https://runkit.com/582de1fb7895530013a26a68/582de22c9cde3d0013427bfe

```js
app.service('todos').find({
  query: {
    completed: true,
    created: { $gt: 'week' }
    $limit: 10,
    $skip: 10
  },
  client: {
    special: 'param'
  }
}
```

which would be

`query[completed]=true&query[created][$gt]=week&query[$limit]=10&query[$skip]=10&client[special]=param`

It's just a simple way for a developer to pass unsafe params that don't make it into the query, and they can use them as they please.

**Comment by marshallswain** [comment]
That sure makes it a pain to type out a query, though.  :)

**Comment by daffl** [comment]
I'm not sure I understand what we'd get from that. Wouldn't we still have the same mapping problem to `params` directly except from `client` instead of `query`?

**Comment by marshallswain** [comment]
As I think about it more, I think the better solution would be to get a hook into `feathers-hooks-common` to move the params from `params.query` to `params.client`:

```js
const moveToClientParams = require('feathers-hooks-common/client-params');

app.service('todos').hooks({
  before: {
    create: [
      moveToClientParams('$customParam1', '$customParam2')
    ]
  }
});
```

Which would move `$customParam1` and `$customParam2` from `params.query` and put them on `params.client`.

**Comment by beeplin** [comment]
>I'm not sure I understand what we'd get from that. Wouldn't we still have the same mapping problem to params directly except from client instead of query?

@daffl I think the difference here is that, if we send both `params.query` and `params.client` back to server, we don't need to worry about `query` being polluted by mixed-in non-query params --  that is, we don't have to call `moveToClientParams` hook before all other hooks in order to extract those non-query params out of `query`. We just directly use `hook.params.client.xxx` in our hooks if needed, or just ignore `hook.params.client` if we don't need to handle them.

**Comment by ekryski** [comment]
> @daffl I think the difference here is that, if we send both params.query and params.client back to server, we don't need to worry about query being polluted by mixed-in non-query params -- that is, we don't have to call moveToClientParams hook before all other hooks in order to extract those non-query params out of query. We just directly use hook.params.client.xxx in our hooks if needed, or just ignore hook.params.client if we don't need to handle them.

That makes sense. We'll just have to be careful and do an audit to make sure that we exclude in the `params.client` object when we pass it to database drivers, etc. So the service adapters would likely need an audit to ensure that passing that isn't going to break anything or allow someone to do something malicious if `params.client` was passed all the way through the backend.

**Comment by eddyystop** [comment]
We should do something as the present way that people use params.query temporarily looks rather hacky.

**Comment by marshallswain** [comment]
Addressing the original post in this issue, maybe we could copy the route arguments into `params.client` to be used the same way.

**Comment by daffl** [comment]
This is now possible using the [client hook](https://docs.feathersjs.com/api/hooks-common.html#client).

**Comment by Creiger** [comment]
Name of the hook has changed to [paramsFromClient](https://feathers-plus.github.io/v1/feathers-hooks-common/#paramsFromClient)
