### ISSUE TITLE
On the client if I try to get a service that does exist it doesn't throw an error.

### ISSUE THREAD

**Issue by miketamis** [feathersjs/feathers#336]
If I do app.service("MyService") but the service name is really "myService" it doesn't throw any error. This can lead to frustrating debugging, it would be awesome if it throwed an error.

**Comment by daffl** [comment]
Unfortunately this is not easily possible other than automatically exposing a list of all available services and their methods and making another additional request when initializing the application. This is mostly a restriction of the websocket libraries because they simply don't to anything when you emit an unknown event. REST endpoints throw a 404 error.

Now that we added https://github.com/feathersjs/feathers-socket-commons/pull/15 you should at least get an error when trying call a method that does not exist (try decreasing the timeout if it takes too long) but because of the limitations of the websocket libraries we support.

There might also be an opportunity for a service registry plugin if someone would be interested in taking that on. A registry service could look like this:

```js
// registry.js
module.exports = function(options) {
  const endpoint = options.endpoint || '/services';
  const app = this;

  app.use(endpoint, {
    serviceInfo(path) {
      const service = this.services[path];

      return {
        path, methods: service.methods
      }
    },

    find() {
      const services = Object.keys(this.services).map(
        path => this.serviceInfo(path)
      )
      return Promise.resolve(services);
    },

    get(id) {
      const paths = Object.keys(this.services);
      for(let path of paths) {
        if(path === id) {
          return Promise.resolve(this.serviceInfo(path))
        }
      }
    },

    setup(app) {
      this.services = app.services;
    }
  });
}
```

Then the client could retrieve that information and check the list if it exists.

**Comment by ekryski** [comment]
@daffl answered this better than I could have. Unfortunately, you'll just have to be careful about spelling 😄. Closing
