### ISSUE TITLE
What’s the correct usage of .sync()?

### ISSUE THREAD

**Issue by sallar** [feathersjs/feathers#358]
Hi, 

I have been trying to use feathersjs and generally it's really great. One thing I don't understand though, is the `sync()` command throughout the generated app and also feathersjs documentation. You casually mention that models have to be synced. This has several problems:

- If the model schema is changed, `.sync()` is not enough and you have to do `.sync({force: true});` which **drops** the table and you lose all your data. You can't also ship a code with `.sync({force: true});` to production, because what if the node app gets restarted for some reason (server fail, etc) and the whole database gets deleted and recreated?
- `.sync()` method by itself tries to run "create table" every time. Is that absolutely necessary?

I tried searching feathersjs docs, issues and also Sequelize docs. Nothing about the importance of this command. So I guess my question is, how do you guys actually deploy your app to production and how you handle schema changes after the deployment?

Thanks.

**Comment by daffl** [comment]
This seems more like a Sequelize question to me since `sync` has nothing to do with Feathers except that it is used by Sequelize models created by the generator. The generated application is really just a suggestion for a recommended Feathers setup and can be changed to whatever you need.

The answers to your questions can probably be found in the documentation for [Sequelize migrations](http://docs.sequelizejs.com/en/latest/docs/migrations/).

**Comment by sallar** [comment]
@daffl Thanks. I figured that might be the answer, just wanted to know your suggestion about this, since feathersjs actually generates an example app...

**Comment by sallar** [comment]
Answering my own question:
https://github.com/sequelize/sequelize/issues/537
Thanks.

**Comment by daffl** [comment]
Nice. Thanks for sharing!
