### ISSUE TITLE
questions before jumping in

### ISSUE THREAD

**Issue by ramsestom** [feathersjs/feathers#368]
Hi

  I just discovered feathers and, from what I've read so far, it seems to be a really powerful framework that should perfectly fit my need :heart_eyes:. 

As a first shot, I will try to develop a tinder like dating app with feathers but I have many questions before starting:
- can feathers handle "temporary" ressources that will only live in ram and be destroyed when transmitted to the receiver(s) (like webrtc signaling messages or live messages that would be sent from one connected user to another but that I do not want to store in a database (of course I could store it into DB and remove it once transmitted but it would not really be efficient))
- if I choose a database type to develop (NeDB) how difficult would it be to switch to another one (MongoDB) before going into production (do I just need to declare MongoDB as my new type of databases and feathers would handle all the database creation and configuration or would I have to do it by hand?)
- Can I easily know which users are currently connected to the server or do I need to store this information somewhere myself?
- How can I perform complex queries between multiple databases (imagine I have a 'users' and 'country' database and want to perform a joint query on both)?
- Can I have multiple services accessing the same database and, in that case, can the ressource returned by each service be partial (for example if I store into 'user' documents of a 'users' database private information concerning the user and public one, can I have a service that return only public information concerning the user and another one that return the private one? Or should I rather have different documents to store public and private information of a user and request them using user _id?) 
- How efficient would a feathers chat server be with thousands (or millions ;) ) of connected clients compared to an XMPP server? would it be pretty much the same or should I expect feathers to be significantly less efficient?

Thanks

**Comment by daffl** [comment]
I think a lot of your questions can be answered by going through the getting started guide (it should really just take an hour) and in the documentation. But to try and answer if possible:

1) Yes. For a ready to go memory storage see [feathers-memory](https://github.com/feathersjs/feathers-memory) but you can always implement [your own services](http://docs.feathersjs.com/services/readme.html) with whatever functionality you need.
2) If you only use the [querying syntax](http://docs.feathersjs.com/databases/querying.html) supported by all adapters you can switch adapters without having to change anything. This does not apply to database specific queries (e.g. advanced MongoDB queries or SQL joins) of course.
3) [This FAQ](http://docs.feathersjs.com/help/faq.html#how-do-i-create-channels-or-rooms) should answer part of the question.
4) Feathers allows cross-service (and database) population with the [populate hook](http://docs.feathersjs.com/hooks/bundled.html#populate). Everything else is mostly up to whichever ORM and database you choose. 
5) You can pre- and postprocess your data using [hooks](http://docs.feathersjs.com/hooks/readme.html). If you store private information separately or remove it in a hook is up to you.
6) Since it is only a thin wrapper over Socket.io Feathers definitely is one of the better libraries to scale. My rule of thumb is ~10k connections per server should be easily possible. It provides *web* APIs however where XMPP is a messaging protocol. You could easily use it as the server for a browser based XMPP chat. As always it is worth pointing out not to worry too much about premature optimization too much though.

**Comment by daffl** [comment]
I'm going to close this. You are welcome to join [our Slack channel](http://slack.feathersjs.com/) if you have any other questions.
