### ISSUE TITLE
Quick Start Prompt Errors at npm start (El Capitain 10.11.6, npm 3.8.3) 

### ISSUE THREAD

**Issue by idkjs** [feathersjs/feathers#386]
After following the steps in the [Quick Start](http://docs.feathersjs.com/getting-started/quick-start.html) I get dropped into this command prompt: local@klik$ from which I can not run npm start. Pic attached. Exiting allows me to run npm start but the program outputs a 404 error page(even if i correct "chat" to "message") Any idea what is going on here? Thanks.
![screen shot 2016-08-09 at 5 37 30 pm](https://cloud.githubusercontent.com/assets/2370391/17523695/d0261b6a-5e5b-11e6-859f-d2e09199a5cc.png)

**Comment by daffl** [comment]
I just ran

```
npm install feathers-cli
mkdir testapp
cd testapp
feathers generate
feathers generate service # call service message
npm start
```

And going to localhost:3030/messages showed what I would expect.

**Comment by aarmand** [comment]
@daffl any idea why i get "local@klik"? I get this working by running "exit" at local@klik prompt. @marshallswain suggested in Slack that the program wasnt exiting out of the generator as expected. Why would this be the case?

**Comment by aarmand** [comment]
Just an FYI to you guys. I ran a 4 generate service commands one after the other. This is what happened. Notice the bold after each series of questions. Sometimes the service exits, sometimes you have to type 'exit' command to get out. It works but I thought i would share since this doesnt seem to be expected.

klik:blog-example klik$ feathers generate service
local@klik~$ 

? What do you want to call your service? graphql
? What type of service do you need? generic
? Does your service require users to be authenticated? No
   create src/services/graphql/index.js
   create src/services/graphql/hooks/index.js
   create test/services/graphql/index.test.js
**local@klik~$ exit** here I had to type exit to move on.

klik:blog-example klik$ feathers generate service
local@klik~$ 

? What do you want to call your service? post
? What type of service do you need? database
? For which database? MongoDB
? Does your service require users to be authenticated? Yes
   create src/services/post/index.js
   create src/services/post/hooks/index.js
   create test/services/post/index.test.js
   create src/services/post/post-model.js

**klik:blog-example klik$ feathers generate service** here generator exited on its own
local@klik~$ 

? What do you want to call your service? comment
? What type of service do you need? database
? For which database? MongoDB
? Does your service require users to be authenticated? Yes
   create src/services/comment/index.js
   create src/services/comment/hooks/index.js
   create test/services/comment/index.test.js
   create src/services/comment/comment-model.js

**klik:blog-example klik$ feathers generate service** here generator exited on its own
local@klik~$ 

? What do you want to call your service? viewer
? What type of service do you need? generic
? Does your service require users to be authenticated? Yes
   create src/services/viewer/index.js
   create src/services/viewer/hooks/index.js
   create test/services/viewer/index.test.js

**local@klik~$ exit** here I had to type exit to move on.
Pic of same below
![screen shot 2016-08-12 at 3 01 41 pm](https://cloud.githubusercontent.com/assets/2370391/17622983/067ed5d2-609e-11e6-8f8f-5a011689a938.png)

**Comment by ekryski** [comment]
Thanks @aarmand. This is resolved with the new release that is coming but we'll leave this open for visibility until that lands.

**Comment by ekryski** [comment]
This is now fixed. `npm install -g feathers-cli@2.0.0`. 💥
