### ISSUE TITLE
Error messages?

### ISSUE THREAD

**Issue by siegesmund** [feathersjs/feathers#396]
FeathersJS seems to emit very few error messages by default. Things like OAuth authentication fail silently with little clue as to the cause. 

Is there a way to address this globally? A loglevel option , for example?

**Comment by daffl** [comment]
You should get errors for everything that happens but have to make sure to `.catch` all [promises](https://www.promisejs.org/) that Feathers returns. For example, using the Feathers client, any authentication error can be caught with something like this:

```js
app.authenticate(options).catch(error => console.error(error));
```

In Node you can add a general uncaught Promise handler like this:

```js
process.on('unhandledRejection', (reason, p) => {
  app.logger.warn(`Unhandled Rejection with reason ${reason}`, reason);
});
```

Since this is not Feathers specific but how Promises work in general I am going to close this issue.

**Comment by siegesmund** [comment]
Thanks, I'll try that.
