### ISSUE TITLE
Bulk 'create' generates multiple events

### ISSUE THREAD

**Issue by sunabozu** [feathersjs/feathers#403]
I've noticed that if I send an array to a `create` method, I get an event for each added resource. And I also suspect that instead of inserting the whole array at once (in MongoDB for example the `insert` method accepts arrays for bulk operations and sends them to the `insertMany` method; it's supported in Mongoose since the 4.4.0 version Automattic/mongoose#723) Feather services do it one by one, which is highly inefficient.

In my case I parse a file with thousands of entries, and I need to insert them as fast as possible. Currently Feathers doesn't help me much with this task.

**Comment by daffl** [comment]
All database adapters use the bulk insertion mechanism provided by the database but you will get an event for each inserted item. If the return value of `create`, `patch`, `update` and `remove` is an array if will send an individual event for each item as one would expect for real-time updates.

**Comment by sunabozu** [comment]
I see, that's reassuring. But I still don't think it should generate an event for each item. It notifies about some action, e.g. creating multiple resources. So it would be logical to get just a single notification with the inserted data as a parameter (i.e. an array). At least that's what I'd expect.

**Comment by daffl** [comment]
We used to do this before but changed it in https://github.com/feathersjs/feathers/pull/179 because all plugins and client libraries expect individual events for each resource. It would be a lot of work for e.g. things like [feathers-reactive](https://github.com/feathersjs/feathers-reactive) to figure out what we are getting back and then determine what to do with it. Since we are using websockets there isn't really that much of an overhead for sending multiple events for batch updates. So thanks for bringing this up and I hope it makes sense now.

**Comment by sunabozu** [comment]
Thank you for clarification.
