### ISSUE TITLE
Creating a feathers-bookshelf Adapter

### ISSUE THREAD

**Issue by frastlin** [feathersjs/feathers#453]
Hello,
I am wondering if an adapter could be created for the ORM built on top of KnexJS
[Bookshelf?](http://bookshelfjs.org/)

Currently the only supported ORMs are:
Mongoose, Sequelize andWaterline. With
[support for Waterline being dropped,](https://github.com/feathersjs/feathers/issues/452)
This means that Sequelize will be the only multi-database ORM.
There looks as if there should be Bookshelf support:
https://www.npmjs.com/package/feathers-bookshelf
But it only talks about Waterline here.
I would love it if both KnexJS and Bookshelf could be supported. This would allow two levels of access if needed.

 What exactly is in the feathers adapters? I'm super new to Feathers, but really love everything I've seen so far. Shouldn't I just be able to npm install Bookshelf and use it as a service?
Thanks,

**Comment by daffl** [comment]
You can indeed just install bookshelf and implement it as a service. That is basically what all the adapters are doing while following some conventions about querying, sorting, pagination etc.

We are using [feathers-service-tests](https://github.com/feathersjs/feathers-service-tests) as the test suite for service adapters to make sure they follow those conventions. You can initialize a new plugin with the standard structure via:

```
npm install yo generator-feathers-plugin
mkdir my-plugin
cd my-plugin
yo feathers-plugin
```

Our reference adapter for how the tests and the service is set up is [feathers-memory](https://github.com/feathersjs/feathers-memory).

If you are interested in creating an adapter for bookshelf we are more than happy to help out any way we can. We are however not planning to add any other ORMs ourselves since we already have two *SQL adapters with Sequelize and Knex and also found that with Feathers services and hooks (for validation and populating related entities) you often don't even need a full blown ORM.

**Comment by daffl** [comment]
Oh and I also forgot to link the [guide for creating a plugin](https://docs.feathersjs.com/guides/creating-a-plugin.html).

I am going to close this issue since, for the reasons outlined above, the team won't take this on as an official adapter but if you would like to give it a shot on we are more than happy to help any way we can.
