### ISSUE TITLE
How it works and does it scale?

### ISSUE THREAD

**Issue by DimitryDushkin** [feathersjs/feathers#454]
I cannot find any information about how "real-time thing" works in feathers and does Feather.js scale to 2-3 instances on different machines? I've read source code, but still do not understand it.

I've found 
> Feathers does it at the service layer

but how Feathers actually do this? Is it store all service-driven changes in internal variable? Or polls DB?

For example, Meteor polls DB or reads MongoDB oplog (which includes all DB changes) and stores DB's slices to sync them on local DB on client. it's clear how it scales. 

But how does it work in Feathers?

**Comment by DimitryDushkin** [comment]
I think I've found information about "how it works" — http://stackoverflow.com/questions/32299935/does-feathersjs-use-the-mongo-oplog-for-live-data-when-mongodb-is-the-databas 

Still it's not clear how it scales.

**Comment by daffl** [comment]
Feathers is just a small wrapper over Express and Socket.io so anything that applies to scaling those works for Feathers as well.

The only Feathers specific scaling related plugin is [feathers-sync](https://github.com/feathersjs/feathers-sync/) which allows to synchronize events across multiple instances of the application (using MongoDB or Redis as the hub).

**Comment by alnour-altegani** [comment]
@daffl do you have any references about express and socket.io scale ?

**Comment by daffl** [comment]
Some references for Express and Socket.io:

- [Express performance best practises](https://expressjs.com/en/advanced/best-practice-performance.html)
- [Using multiple nodes for Socket.io](http://socket.io/docs/using-multiple-nodes/)

More Feathers specific:

- [feathers-sync](https://github.com/feathersjs/feathers-sync/)
- [Using Feathers as a real-time API proxy](https://blog.feathersjs.com/using-feathersjs-to-make-your-existing-api-real-time-813f7c3fd892#.vfchsy479)
- [Feathers Services](https://docs.feathersjs.com/services/readme.html)
- [Issue for documenting transitioning to microservices](https://github.com/feathersjs/feathers-docs/issues/70)

The last point is still open but basically Feathers doesn't really care if your service is a database or makes request to a remote service or even another API. So it is already possible to distribute each service onto its own instance and connect them using [Feathers client](https://docs.feathersjs.com/clients/readme.html).

The Auk docs will also contain a section about how it all fits together (see https://github.com/feathersjs/feathers-docs/issues/251).

Closing since this is a pretty open ended question and I linked several resources and related more specific issues.

**Comment by DimitryDushkin** [comment]
Thanks. feathers-sync is exactly what I was looking for. May be mention it in docs?

**Comment by daffl** [comment]
Definitely. It needs some final polish but we'll definitely include it in the documentation for the next release.
