### ISSUE TITLE
How to filter events for the original connection who emitted this event?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers#455]
Suppose connection A creates something via a service, and then A gets the created data back in a callback or a promise. Then A gets another (same) created data via the `created` event. So the same thing gets received twice.

Is there any way to tell which connection is the original connection where the `create` behavior comes from, and then we could filter it? I checked the params of the filter function (data, connection, hook) but got no clue.

Or this is not worthy filtering the redundant data transfer since the filter would cost even more?

**Comment by daffl** [comment]
In general filtering out the sender shouldn't be necessary. Clients should listen to all events to update the application in real-time.

I usually just use the promise handler to know that the call succeeded (to handle the error and maybe show a "Saved" message) but not to update the application since that should already happen for everything through real-time events.

**Comment by beeplin** [comment]
get it. I can judge from client side if socket.io is on. if does, discard the promise-returned data and wait for the coming event.
