### ISSUE TITLE
Login after account creation

### ISSUE THREAD

**Issue by Igorpollo** [feathersjs/feathers#467]
I'm using the chat demo app from the docs to learn...

In the `middleware/signup.js` I want to automatcly login the user after he created a new account.

I'm trying this whithout success..

`'use strict';

module.exports = function(app) {
  return function(req, res, next) {
    const body = req.body;

    // Get the user service and `create` a new user
    app.service('users').create({
      email: body.email,
      password: body.password
    })
    // Then redirect to the login pos
    .then(user => res.redirect('auth/local'))
    // On errors, just call our error middleware
    .catch(next);
    };
   };`

Can someone open my mind?
How can I loggin the user after he created his account?
Thanks

**Comment by marshallswain** [comment]
I think the easiest way would be to change the signup form so that it uses an Ajax call.  Then you can just do `app.authenticate()` on the client with the new token.  If you don't use an Ajax call,, you'd have to set the token in a cookie and read the cookie from the client after the redirect.  Sorry I don't have time to provide example code.

**Comment by Igorpollo** [comment]
@marshallswain its a good solution. But I authenticate with token? isnt with email and password, like the docs below?

    // Authenticate. Normally you'd grab these from a login form rather than hard coding them
     app.authenticate({
    type: 'local',
    'email': 'admin@feathersjs.com',
    'password': 'admin'
     }).then(function(result){
     console.log('Authenticated!', app.get('token'));
     }).catch(function(error){
      console.error('Error authenticating!', error);
     });.error('Error authenticating!', error);
     });

**Comment by marshallswain** [comment]
Heh.  I was pretty tired and only half coherent.  So the workflow will be something like this:

1. Submit the form to create the user over an Ajax request to `/signup` or whatever you've setup for that.
2. Create the user on the server, then do `app.authenticate()` with username/password on the server, which will give you back a token.
3. Return the token in the response to the client.
4. Call `app.authenticate({type: 'token', token: '<token>')` on the client. You can either pass what you put above, or do `token` auth instead of `local`.

Note that if there's a redirect of any kind, whether on the client or the server, the client will have to be reauthenticated using the token.  If you setup the authentication client plugin to use `storage: window.localStorage`, then it will store the token between refreshes so you'll have access to it on the next page.  You can then run `app.authenticate()` and pass nothing and the current version of feathers-authentication on the client will automatically do a token login if it finds the token in `localStorage`.

**Comment by Igorpollo** [comment]
@marshallswain thansk for the reply.
I think this way gonna work.
But, I'm trying to think in some code in backend...I think I'm doing wrong in express basics...
I need to put the `app.post` inside `.then()` or call it after the creation, like this:
     
     var body = req.body
    // Get the user service and `create` a new user
      app.service('users').create({
      email: body.email,
      password: body.password
      })
      // On errors, just call our error middleware
      .catch(next);

      app.post('/auth/local', function(req, res) {
       req.body(body)
      });

**Comment by daffl** [comment]
Sorry, I thought this one had been figured out already. `auth/local` is also a service so to log in (create a token) you have to `create` a new token with that information:

```js
  const { email, password } = req.body;
  const userInfo = { email, password };

  // Get the user service and `create` a new user
  app.service('users').create(userInfo)
  .then(() => app.service('auth/local').create(userInfo))
  .then(authInfo => {
    // do something here with authentication information
  })
  // On errors, just call our error middleware
  .catch(next);
```

Closing since it's been open for a while and I hope there is enough information now but please reopen if you have any other questions.

**Comment by tguelcan** [comment]
@daffl  i get this error with 'auth/local' service

info: error: authentication - Method: create: Cannot read property 'create' of undefined
error:  TypeError: Cannot read property 'create' of undefined

`module.exports = function(options = {}) {
  return async context => {
    // Get `app`, `method`, `params` and `result` from the hook context
    const {
      app,
      method,
      result,
      params
    } = context;

    await app.service('auth/local').create(context.data).then(authInfo => {
      console.log(authInfo)
    });
    // Best practise, hooks should always return the context
    return context;
  };
};
`
