### ISSUE TITLE
Feature Request: Better Fullstack Dev Support

### ISSUE THREAD

**Issue by georgeedwards** [feathersjs/feathers#481]
I am trying to integrate feathers to my existing expressJS/Angular2 and have ran into a few hurdles which I think highlight an opportunity for improvement. 
The scenario I think would be worth considering is if someone if developing a full stack application, with a client directory and a server directory. In my case the [angular-cli](https://github.com/angular/angular-cli) is managing the client directory. 

The first issue is that of paths, it would be useful to either be able to set the directory on generation e.g. `feathers generate -p ./server` and from then on, generating a service etc. from the project root would recognise the desired root and generate the service in `server/src/services/xyz` rather than creating an src dir in the project root. 

I think it would be great to then cover the scenario I describe in a tutorial/docs. I am happy to contribute this.

**Comment by daffl** [comment]
What we usually recommend for the frontend setup is

1. Use the `public/` folder (once generated you can always change its location). I then usually build  into `public/dist` and host that folder in production
2. Create an entirely separate project for the frontend. This is what we usually recommend when there are any special requirements

I'm not entirely sure what we could do to improve this without becoming too concerned about specific frontend frameworks especially since the most common case I know of is to create a separate frontend project.

Side note: We're still really looking for help with the chat guide for Angular 2.

**Comment by daffl** [comment]
I'm going to close this for https://github.com/feathersjs/generator-feathers/issues/158 since it is more specific and I think what you are suggesting as a start. If there are any other suggestions, please open a new issue in the generator-feathers repository.
