### ISSUE TITLE
Is there a way to wrap multiple DB services in a SQL transaction?

### ISSUE THREAD

**Issue by eblanshey** [feathersjs/feathers#493]
Say I have a service that does a lot of actions to create a purchase order. It can utilize the following standard DB services:

- `CREATE` purchase order
- `UPDATE` user fund balance
- `PATCH` item quantity left in stock

Assuming I use Knex, how can my `/order` service wrap the other services in a DB transaction to ensure ACID compliance? Or am I out of luck in using those services and will need to make custom queries by hand?

Thank you.

**Comment by eblanshey** [comment]
Thanks for the response. When I get to the stage where I need it (and I will) I'll be sure to update this with my findings.

**Comment by rollymaduk** [comment]
@eblanshey  you might find http://www.apollodata.com  useful/interesting , it is based on facebooks graphql, I even wrote a nice little feathers plugin here https://github.com/rollymaduk/feathers-apollo-server

**Comment by daffl** [comment]
I am not sure what Apollo can do for making things happen in a transaction. What database adapter are you using? There is an issue about transactions in the Knex adapter at https://github.com/feathersjs/feathers-knex/issues/91

**Comment by marshallswain** [comment]
My original answer pretty much sums up how this would have to work, so I'm going to close this.  @eblanshey we'd love updates posted here whenever you have them.  Thanks!

**Comment by idibidiart** [comment]
I think the db has to support two-phase commit AND you have to inplement some form of concurrency control to avoid an inconsistent state. The latter only needed if multiple users can mutate the same resource concurrently but you can serialize operations (by queuing) to avoid that. The former, 2PC, is needed if you want to have the ability to run a set of dependent mutations asynchronously (promise chained across multiple services) and be able to rollback in case a conditional update fails (due to consistency constraints you specify in the condition to your update) or the server crashes in the middle of executing the async flow.
