### ISSUE TITLE
feathers-rest, how to query using $in?

### ISSUE THREAD

**Issue by davigmacode** [feathersjs/feathers#497]
### Steps to reproduce

call api using feathers rest client

`app.service('platforms').find({
            query: {
              _id: {
                $in: [1, 3, 6]
              },
              $sort: { fans: -1 }
            }
          })`

### Expected behavior
return platforms collection filtered by _id $in [1,3,6]

### Actual behavior
return all platforms collection because the _id filter $in not generated to the query string

### System configuration

**NodeJS version**:
6.9.1

**Operating System**:
Win 10

**Browser Version**:
Chrome

**Comment by davigmacode** [comment]
it is actualy works when the array of _id is not empy

**Comment by daffl** [comment]
It looks like this is how Node's [querystring](https://nodejs.org/api/querystring.html) module behaves (see https://github.com/nodejs/node-v0.x-archive/issues/7971 for a discussion). Since it is using URL strings, there is always limitations (e.g. conversion and things like empty values etc.) imposed when using the REST clients (this is not an issue when using websockets).

Adding `null` (like `{ $in: [ null ] }`) seems to make it work (but it might not be converted back into an empty array). The extended query parser [qs](https://github.com/ljharb/qs) seems to behave the same way so I don't think there is much we can do.
