### ISSUE TITLE
How to do Socket.io Authentication

### ISSUE THREAD

**Issue by anoopmd** [feathersjs/feathers#514]
Say suppose, I am building a realtime application using FeathersJS socket.io and the client obtains the JWT from an different server (Not the FeathersJS server), then how do I authenticate the incoming socket connections on the FeatherJS server using the JWT.

To clarify,
Server A : Gives you a JWT
Server B : FeathersJs Server
Client : Talks to Server A and gets the JWT. Now it needs to talk to ServerB.

Should I use something like socketio-jwt (https://github.com/auth0/socketio-jwt)
OR do you have any alternate recommendations ?

Thanks in advance.

BTW FeathersJS is Awesome !!

**Comment by marshallswain** [comment]
@anoopmd, do you have full control over serverA and serverB?  You would need to program serverB so that it has a reliable method of verifying the token received from serverA.  We already have a great solution for putting together extremely flexible authentication with the new prerelease version of [feathers-authentication](https://github.com/feathersjs/feathers-authentication/tree/master).  I'm fairly certain that you would be able to use the new [feathers-authentication-local plugin](https://github.com/feathersjs/feathers-authentication-local#customizing-the-verifier) with a custom verifier to do what you want to do.  The first step will be to upgrade your application to feathers-authentication@1.0.x.  This is still a pre-release version.  It's fully ready for use, but the docs are pending.

**Comment by marshallswain** [comment]
Issue moved to [feathersjs/feathers-authentication #462](https://github.com/feathersjs/feathers-authentication/issues/462) via [**ZenHub**](https://www.zenhub.com/)
