### ISSUE TITLE
Consider redesigning the Socket provider event format to move service and method into the payload.

### ISSUE THREAD

**Issue by edwardmsmith** [feathersjs/feathers#521]
When you call, from the feathers client, a non-existent service, or a non-existent method on an existing service over the Socket provider, you end up waiting for the socket timeout.

This is because there is no cross-library way to figure out if an event is listened-to or not other than a timeout.  You can't listen to all events.

The Socket provider's events currently have the format `emit('<servicepath>::<methodname>', <data>)`

If the format was changed to something like `emit('feathers-event',{service: <servicepath>, method: <methodname>, ... })` then the server could determine if the service and method exist, and if not, callback with an error.

**Comment by ekryski** [comment]
Valuable point @edwardmsmith but this would be a **massive** breaking change, so it's definitely not something that would happen soon I don't think. I'll put it on the table with the team to discuss for the next release after Auk and see what people think since we're likely going to be revisiting the event system anyway.

**Comment by daffl** [comment]
I asked @edwardmsmith to log the issue since he brought it up in Slack and it made a lot of sense. It is indeed a pretty serious change unless we set up both, the old and new event handlers.

The big advantage would be that we could finally send back errors e.g. when the service or method name does not exist (instead of just timing out). We could also move authentication special events and things like that into that namespace making things more self contained.

**Comment by daffl** [comment]
I was thinking about this a little more and maybe we can get this into the next version (and make things backwards compatible). What I propose it to change the [direct connection format](https://docs.feathersjs.com/api/socketio.html#direct-connection) to take the calls int he form of `('methodname', 'servicename', ... parameters, callback)`, for example:

```js
socket.emit('find', 'messages', {
  query: { status: 'read', user: 10 }
}, (error, data) => {
  console.log('Found all messages', data);
});

socket.emit('get', 'messages', 1, {
  query: { fetch: 'all' }
}, (error, message) => {
  console.log('Found message', message);
});

socket.emit('create', 'messages', {
  "text": "I really have to iron"
}, (error, message) => {
  console.log('Message created', message);
});
```

We can also still add the backwards compatible event listeners for the old format.

This change would allow us to

- Only set up one event handler for each of the service methods
- Send back an error when e.g. trying to call a non-existing service or method instead of just timing out
- Get rid of the message format (`servicename::event`)
- Potentially allow parameterized service names like in REST routes (e.g. `users/123/messages` for `users/:userId/messages`)

The real-time event format (e.g. `messages created` or the general `<servicename> created`) and event filtering would stay the same (although we could also add a general `created` event which would receive a "safe" form of the hook object).

**Comment by corymsmith** [comment]
I think this is awesome, I've run into issues a bunch of times due to the timeout w/ non-existing services or typos so it would be nice to essentially `404` in those cases.

Preserving backwards compatibility is key here.

The Swift client will have to support the new format eventually and will have to specify which version of feathers its compatible with.

**Comment by ekryski** [comment]
@daffl if you think we can make it happen I'm all for it, for all of the reasons you mentioned and timeouts to non-existent methods. I think it will make debugging socket calls a bit easier.

The only thing I'd want to make sure is that we're able to keep a fairly similar interface when dealing with other types of transports (ie. MQTT, AMQP, ZeroMQ, etc.). I don't see why not because it would be the transport adapter that would do the translation, but just throwing that out there.

> The Swift client will have to support the new format eventually and will have to specify which version of feathers its compatible with.

Good point @corymsmith. @startupthekid you have any thoughts/concerns?

**Comment by startupthekid** [comment]
@ekryski Hmmm no concerns from my side, I can see specifying the new/old format being as simple as passing in a configuration object to the socket provider.
