### ISSUE TITLE
Incorrect typings for TypeScript

### ISSUE THREAD

**Issue by sinedied** [feathersjs/feathers#525]
I'm currently building a new app from scratch based on feathers, and I'm using TypeScript through `ts-node`.

So far so good, except I found issues with the typings, for example:
- no method `remove` is defined on `feathers-hooks` definition
- `Service` definition has all service methods mandatory, whereas only one is required in practice

From what I've seen in #381, typings seems mostly experimental at this stage, am I correct?

What would be the preferred strategy to report those kind of issues, regroup all found issues related to typings into 1 github issues or post individual issues? Should I submit directly a PR to fix this without the need of a related issue?

**Comment by marshallswain** [comment]
Hi @sinedied, our the core team's current view on typescript is found in [this comment](https://github.com/feathersjs/feathers/issues/381#issuecomment-284596100).  I don't know what it's going to take to make it happen (because I don't use TypeScript).  We need to find a new repository as a home for TypeScript issues, so we can continue to focus on the stuff that's fun for us.   f you want to start the process, it would make life easier for us.  As mentioned, none of us have found the lack of TypeScript to be painful enough to start using it, so we have zero experience with it.  ;)

**Comment by daffl** [comment]
We are however taking pull requests for what is currently provided. So if you are able to fix your issues we will take pull requests and release it.

**Comment by sinedied** [comment]
@marshallswain It would be sad to move the definitions outside of the project's scope, even though I understand the team's view on this. TypeScript compatibility was one of the selling points of feathers for me.

I'm current working on a feathersjs/typescript + jasmine/supertest starter kit, to make it easier to onboard on a stack like this, maybe playing with it could help you seeing the TypeScript benefits 😄 

I'll try to propose a PR once I have a working base with the fixed typings.

**Comment by eddyystop** [comment]
We would love TS PRs.

TS was a Feathers' community initiative and it would be lovely if that
community had enough incentive to maintain it.

**Comment by marshallswain** [comment]
Issue moved to [feathersjs/feathers-typescript #2](https://github.com/feathersjs/feathers-typescript/issues/2) via [**ZenHub**](https://www.zenhub.com/)
