### ISSUE TITLE
Feathersjs in CRUD based on stored procedures for application on production

### ISSUE THREAD

**Issue by maxprog** [feathersjs/feathers#529]
Hi Eric

I’m interested in using feathersjs in production environment. But most of clients use stored procedures (tsql) on microsoft sql server.
Could You recommend documentations or samples (source codes) in case of using feathersjs where services (http requests) in case of CRUD operations are basing on stored procedures (tsql) (not tables) e.g. 
post  -  create - “exec product_create param1,param2,param3"
put - update - “exec product_update param1,param2,param3”
delete -  “exec product_delete param_id”
get - find - “exec product_list param1,param2..”

Best Regards
Greg Kroczek

**Comment by marshallswain** [comment]
@maxprog, This is probably already supported by the feathers-sequelize adapter.  I would imagine it's not a change that would occur in Feathers, but something that you would change in a Sequelize model so that it uses the stored procedures instead of tables.  I would search for any information on `Sequelize Stored Procedures`, and maybe start with this link: http://stackoverflow.com/questions/29280785/calling-stored-procedures-in-sequelize-js

Hopefully that will have some information on how you would setup Sequelize.  If you can use Sequelize, then you more than likely can just use feathers-sequelize and won't have to create your own service adapter.
