### ISSUE TITLE
 I have a doubt - API | PHP | MYSQL

### ISSUE THREAD

**Issue by GlauberF** [feathersjs/feathers#543]
### I have a doubt

Hello, I'm Brazilian and I liked the framework, my doubt.
Would you like some tutorial or video, where do you integrate Feathers with an existing api (PHP)?

Another question has some post, creating api with feathers and using mysql as database?

**Comment by letminin** [comment]
Well, you will find tons of examples, tutorial by searching on google and documentation (the lastest version auk realease is still in progress but already deployed, if anyone can correct me), we also add a repo dedicated to tutorial with more examples.
About the question of coupling feathers within your existing API, not sure to fully understand the question, but no php sdk or any feathers php client is available.

**Comment by marshallswain** [comment]
@letminin, yes, the next releases are already available, and we're working on docs, so you're right.

@GlauberF I recently made the [feathers-postmark](https://www.npmjs.com/package/feathers-postmark) adapter.  You can see [here](https://github.com/feathersjs/feathers-postmark/blob/master/src/index.js#L3) where I bring in the postmark package, (which is basically their own HTTP client).  This particular plugin only implements the [`create`](https://github.com/feathersjs/feathers-postmark/blob/master/src/index.js#L25) method, currently.  The `create` method simply [makes a request](https://github.com/feathersjs/feathers-postmark/blob/master/src/index.js#L40) using the HTTP client.  Since the postmark plugin uses callbacks and not a promise, I [wrapped it in a promise](https://github.com/feathersjs/feathers-postmark/blob/master/src/index.js#L38) and used [resolve](https://github.com/feathersjs/feathers-postmark/blob/master/src/index.js#L44) for the result and [reject](https://github.com/feathersjs/feathers-postmark/blob/master/src/index.js#L42) for the error.  That's all it takes.  You don't even have to use an ES6 class, as I've done there.  You can just pass a plain object literal with the methods you want implemented.  It's especially simple if your HTTP client uses promises.

```js
const myHttpClient = require('my-specific-http-client')
{
  create: function (data, params) {
    return myHttpClient.makeRequest({})
  }
}
```

**Comment by marshallswain** [comment]
Please reopen if your doubt has not been resolved.
