### ISSUE TITLE
Cannot Login a user if the record exists in MongoDB?? Using Auth0

### ISSUE THREAD

**Issue by thebasix** [feathersjs/feathers#549]
When I use memory to store users I can go to /auth/auth0 as many times I want to authenticate a user.

But when I do that while using Mongo, if the record with the exact _id doesnt exist in Mongo collection, the login will be successful. But if I login successfully the first time the record with _id is created in Mongo, then if I try the second time, I get redirected to /auth/failure with msg "something went wrong, try again later". I cannot relogin unless I drop collection.

I cannot even login with facebook oauth if the record exists in Mongo.

Any idea to why is this happening?

**Comment by marshallswain** [comment]
There are a lot of variables in the setup that could cause things to go wrong, so it's hard to tell what the issue is.  It would be a good idea to set up some breakpoints in the `feathers-authentication-oauth2` plugin in your `node_modules` folder and see if you can get a better idea of where it's failing.  If you don't already have a good debugger for node, I wrote an article you can use to start debugging: https://blog.feathersjs.com/debugging-feathers-with-visual-studio-code-406e6adf2882?source=activity---post_recommended

**Comment by daffl** [comment]
Also, are you using feathers-authentication v1.x? If not, can you try your setup with the latest `feathers-cli@^2.0.0` (`npm install feathers-cli -g`).

**Comment by thebasix** [comment]
Updating package to v2 solved the issue.
