### ISSUE TITLE
Microservice database per service?

### ISSUE THREAD

**Issue by kethan** [feathersjs/feathers#552]
Hi,

How do I achieve Database per service with different databases schema? If I have User service using MongoDB with reference to Post Service using MySql. How do I achieve this?

Only option is Waterline or Loopback ?

**Comment by marshallswain** [comment]
All of the database adapters would support this.  You just have to follow each adapters documentation to setup a database connection, then pass it to each adapter when you create a service.  To achieve the references between services, you would use the populate hook from Feathers-hooks-common.

**Comment by kethan** [comment]
@marshallswain 
Thanks, But How do I refer  posts : [{ type: Schema.Types.ObjectId, ref: 'Post' }] with that of Post of MySql schema

**Comment by marshallswain** [comment]
You don't use Mongoose to refer to posts.  This is where the `populate` hook comes in.  If you define something in a Mongoose schema, it expects it to be in MongoDB.  Your Mongoose schema should only contain what will be in the MongoDB collection.  Same for your MySQL schema and table.  Those two technologies won't play together. But, if you set each up as its own individual service with its own independent database connection, the Feathers service interface makes it happen.

The steps to making this work are:
- Setup the `users` Mongoose service, leaving it completely unaware of the `posts` service.
- Setup the 'posts` service, leaving it completely unaware of the `users` service.
- Use the populate hook, so that when data from one is requested it populates the data from the other.  Let's imagine you populate the user data so each `user` record contains a `posts` field.

There are two ways to handle this for the client:
- Setup clients so that whenever they publish updates to the `posts`, it's directly to the `posts` service.  **OR**
- Setup clients to only talk to the `users` service, and use hooks on the server to watch for any changes to the `posts` field and reference the `posts` service by doing `hook.app.service('posts').patch()`, etc.

**Comment by kethan** [comment]
@marshallswain Thanks for answering. :)

So you are saying I should not refer any foreign key? If so how will I know these are the posts of a specific user?

**Comment by marshallswain** [comment]
Go ahead and store the foreign keys in the data. Just don't tell either ORM to populate them.  Then populate them in a hook.  The populate hook will use the keys to pull from both services.

**Comment by kethan** [comment]
@marshallswain  Thanks that should be fine.

**Comment by kethan** [comment]
Hi @marshallswain 
Is the following correct way of coding microservices per database?
```javascript
/////////////  Mongoose  /////////////
var UserSchema = Schema({
  name    : String,
  age     : Number,
  posts  : String  //Reference as string is that ok??
});
/////////////  Mongoose  /////////////


/////////////  Sequelize  /////////////

const PostSchema = sequelize.define('Post', {
    title: {
      type: Sequelize.STRING,
      allowNull: false
    },
    body: {
      type: Sequelize.STRING,
      allowNull: false
    } ,
     userId: { // Reference as string is that ok??
      type: Sequelize.STRING,
      allowNull: false
    },
    freezeTableName: true
  });

/////////////  Sequelize  /////////////

//////// Populate //////// 
const userRoleSchema = {
  include: {
    service: 'posts',
    parentField: 'posts',
    childField: 'userId'
  }
};

app.service('users').hooks({
  after: {
    all: populate({ schema: userRoleSchema })
  }
});
/////// Populate //////// 
```

**Comment by marshallswain** [comment]
I have yet to use the new `populate` hook.  @eddyystop can you take a look? ^^^

**Comment by eddyystop** [comment]
Feathers requires POJOs. Sequelize returns ORMs rather than POJOs unless you specify `raw: true`.

You have to include `{ query: { raw: true } }` on your original service calls so the base results are POJO.

To get POJOs for the joined records, you have to specify:
```javascript
const userRoleSchema = {
  include: {
    service: 'posts',
    parentField: 'posts',
    childField: 'userId',
    query: { raw: true }
  }
};
```

**Comment by kethan** [comment]
@eddyystop Oh thank you :+1:   I have a doubt giving string or int for reference or foreign key is that ok? or is there any other better way?

**Comment by eddyystop** [comment]
`populate` will create a `find` with `{ query: { userId: posts } }` where, of course, posts will evaluate to the value in the base record. So int to int, or string to string compares will work.

**Comment by kethan** [comment]
@eddyystop  Super :+1:  Now I am clear
