### ISSUE TITLE
405 Method not allowed for a simple service route

### ISSUE THREAD

**Issue by Mr-Binary** [feathersjs/feathers#652]
### Steps to reproduce

1. `feathers generate app`
2. `feathers generate service` -> default mongoose service with a `users` model
3. use browser access `http://localhost:3030/users/` works, gives correct result
4. follow this [instruction](https://legacy.docs.feathersjs.com/rest/readme)
5. add the following code
```javascript
app.use('/users/:userId/pocket/:pocketId', {
  get(id, params) {
    console.log(params.query); 
    console.log(params.provider); 
    console.log(params.userId); 
    console.log(params.pocketId);

    return 123;
  }
});
```
The position is

```javascript
app.configure(rest());

// Add it here

app.configure(middleware);
app.configure(services);
app.use(notFound());
app.use(handler());
app.hooks(appHooks);
module.exports = app;
```

### Expected behavior
Open the URL in Chrome: 
`http://localhost:3030/users/1/pocket/2`
See `console.log` in command line

### Actual behavior
Output the following in the Chrome console:
`GET http://localhost:3030/users/1/pocket/2 405 (Method Not Allowed)`

### System configuration
All things are using latest release version

### When it works
It works when I generate a custom service in this route `/users/:userId/pocket`, and modify the code in `pocket.class.js`
Any idea why?

### Beside this:
Have a question, given that I already have an API endpoint like `/users` in this case, how could I have a combined router like `/users/:userId/pocket/:pocketId` ?
The way that I did in `When it works` section, is it the recommend way?

Or should I build a custom service which using a router like this ? `/like?userId=XXX`

**Comment by daffl** [comment]
Does it work if you add it after `app.configure(services);`?

**Comment by daffl** [comment]
Also, you have to `return Promise.resolve({})` with an object for everything to behave properly.

**Comment by Mr-Binary** [comment]
Thanks, but still not work, I mean, with the `Promise` and altering its order.
Not a big deal, since a custom service could solve it. 
But I just think it will block the newbie to the framework like me.

**Comment by daffl** [comment]
Your problem is that you are trying to define the full route instead of the actual service name. In your case you are registering a service at `http://localhost:3030/users/:userId/pocket/:pocketId`. This means that `/users/1/pocket/2` will try to call the `find` method with `params` `{ userId: 1, pocketId: 2 }`.

To trigger the `get` method you would have to call `/users/1/pocket/2/test` which would call `get` with `params` `{ userId: 1, pocketId: 2 }` and the `id` being `test`. If you want to hit the `get` method with the route you provided the path should be

```js
app.use('/users/:userId/pocket', {
  get(id, params) {
    console.log(params.query); 
    console.log(params.provider); 
    console.log(params.userId); 
    console.log(params.pocketId);

    return 123;
  }
});
```

In this case the order (after or before `app.configure(services)`) also won't matter (as long as it is before the `notFound` middleware.
