### ISSUE TITLE
[Proposal]: Empty POST requests should error

### ISSUE THREAD

**Issue by teddy-error** [feathersjs/feathers#722]
There was a decision made to normally process requests where posts contain no data in the body. I struggle to imagine what scenario that might be a use case. For instance, suppose the header data contains sufficient information to facilitate a meaningful server action. What would that scenario be?

Rather than throwing an error or warning, Feathers instead creates an empty object.

### Steps to reproduce
Generate an application and a service mapped to a database

### Expected behavior
```
> POST /messages HTTP/1.1
> Host: localhost:3030
> Accept: */*
> Accept-Encoding: deflate, gzip
> Content-Type: application/json
> Content-Length: 0
< HTTP/1.1 500 Error
```

### Actual behavior
```
> POST /messages HTTP/1.1
> Host: localhost:3030
> User-Agent: insomnia/5.10.1
> Accept: */*
> Accept-Encoding: deflate, gzip
> Content-Type: application/json
> Content-Length: 0
< HTTP/1.1 201 Created
```

**NodeJS version**:
`8.7.0`

**Comment by teddy-error** [comment]
> You could just create an app `before` hook that throws an error if `create` gets an empty object.
- @daffl

I think it is worth considering whether accommodating (what seems to me) an unlikely use case or giving the user a meaningful error message when an unlikely scenario is occurring. For instance, by accidentally omitting the `content-type` header of a request the default-configured `body-parser` will ignore the body resulting in the outcome I described.

**Comment by daffl** [comment]
Feathers tries to deviate from standard Express behaviour as little as possible because experience has shown that any assumption will at one point break down for someone. Maybe an empty object is allowed and will just create a new entry with all the default settings?

So if the bodyParser gives you an empty object that's a case that has to be handled in every other Express application as well. In Feathers case this can be done with a two-line `before` `create` application hook:

```js
app.hooks({
  before: {
    create(context) {
      if(!context.data || Object.keys(context.data).length === 0) {
        throw new Error('Content can not be empty');
      }
    }
  }
});
```

**Comment by daffl** [comment]
Closing for the reasons outline above. Thanks for bringing this up though!
