### ISSUE TITLE
How to filter on referenced models

### ISSUE THREAD

**Issue by LazyFatArrow** [feathersjs/feathers#727]
I have two models A and B with 1:1 relationship, I'm using the populate hook to populate B inside A and using the query option to filter on the B model, if there is no result from B it populates null into the reference inside A. I want it to only return results where the query has been fulfilled with pagination. is that feasible with hooks?

**Comment by daffl** [comment]
You can always remove properties in an after hook via

```js
const { omit } = require('lodash');

function(hook) {
  if(hook.result.reference === null) {
    hook.result = _.omit(hook.result, 'reference');
  }
}
```

`delete hook.result.reference` would work as well but Lodash's `omit` is a little safer because it makes a copy and more flexible because it allows dot separated keys.

There is also the [pluck common hook](https://docs.feathersjs.com/api/hooks-common.html#pluck) which does something similar.
