### ISSUE TITLE
How can I join a channel after a service method runs?

### ISSUE THREAD

**Issue by AmrN** [feathersjs/feathers#744]
I have a custom service that allows users to subscribe to a room through its `create` method. But now I am wondering how to join that room's channel to receive future messages. 
I thought about something like this:

```js
app.service('room-subscriptions')
 .on('created', (data) => {

   // how can I access connection?
   const connection = {};

   app.channel(`rooms/${data.roomId}`).join(connection);
 });
```

Unfortunately I couldn't figure out how to access the current connection here similar to this: 
```js
app.on('connection', connection => {});
```
or
```js
app.on('login', (user, { connection }) => {});
```

**Comment by daffl** [comment]
You can [filter](http://buzzard.docs.feathersjs.com/api/channels.html#channelfilterfn) all channels and return a new channel that has only the connections from a given user (or any other condition):

```js
// Returns a new channel with all connections of the user with `_id` 5
const userFive = app.channel(app.channels)
  .filter(connection => connection.user._id === 5);
```

**Comment by AmrN** [comment]
Thank you for the quick response. 
One more thing, what's the preferred way of accessing the current user inside an event handler?
I noticed that it gets passed the context/hook as the second argument and I can access the user there, is this correct? 
```js
app.service('room-subscriptions')
 .on('created', (data, context) => {
    const user = context.params.user;
 });
```
I'm asking this because I couldn't find that second argument mentioned anywhere in the [events documentation](https://buzzard.docs.feathersjs.com/api/events.html).

**Comment by daffl** [comment]
You are totally right. I will add it to the docs.

**Comment by AmrN** [comment]
Thanks again. Feel free to close this issue.

**Comment by hdngr** [comment]
@daffl - I have the same question, and is there a way to get the user's connection when no channels have yet been initialized.

In my use case, the user will not be a part of any channels initially so

```
const userFive = app.channel(app.channels)
  .filter(connection => connection.user._id === 5);
```

Will not work.

It seems like the simplest thing would be if `connection` hung off of the hook context:

```
app.service('room-subscriptions')
 .on('created', (data, {connection, ...rest}) => {
   app.channel(`rooms/${data.roomId}`).join(connection);
 });
```

Also, please correct me if I am wrong, but the only way to access connection data and properly join a channel is as outlined [here](https://docs.feathersjs.com/api/channels.html#channeljoinconnection)?

Because I take a super modular approach to how my apps are organized, I'd like to be able to easily join/leave channels in the context of service events, methods, or hooks.  Is there a better option?

**Comment by daffl** [comment]
Every connection that you need should at least join one channel (e.g. `authenticated` for every connection on `login`), then you will continue to have access to it.

https://github.com/feathersjs/docs/issues/950#issuecomment-352301687 should have the answer to the rest of your question.

**Comment by daffl** [comment]
The hook context connection might not be necessarily the connection that you are targeting. E.g. someone else could make you join a channel or one user is connected with multiple clients (e.g. phone and browser - you want both to join any new channels).

**Comment by hdngr** [comment]
Actually, you hit my use case.  I have a "room" (channel), that opens in a new browser window (and with a new socket id).  There are certain updates  I need to run when the "room" is closed (`on('disconnect'`) that I don't want to effect the other window.  E.g. `{userCheckedIntoRoom: false}` but `{userOnline: true}`.

So, the blanket events, 'login' and 'disconnect' are too general, since without more data, the server does not know whether the user is in the room or not.

To get more specific, when a user goes to a room I patch the room with {'userCheckedIn': true}.  The problem is that no where in the event chain hook, service method, publisher, am I able to get access to the specific socket that is calling the "patch" method.

Perhaps I should set a property on `socket.feathers` to indicate whether the user's socket should subscribed to only "room" events?  e.g. `socket.feathers.roomId`  This way when I "patch" a room or a user closes a socket I only update data related to that room.

Thanks for your quick reply!

**Comment by hdngr** [comment]
My socket authentication scheme on the client is coupled with a React HOC that sits above the entire app, not just the "rooms" page.

I think what I will do now is enrich the socket authentication:
```
// on client
app.authenticate({
            strategy: 'jwt',
            accessToken: token,
            roomId // can be falsey
          }) 
```

```
// server
app.on('login', (user, { connection }) => {
    app.channel('authenticated').join(connection);
```

and then on the server any time I need to access the connection specific to a room (if the user has multiple connections I can user your solution

```
// check user into or out of a room
app.service('rooms').on('patched', (roomId, data, { params }) => { 
   // user checking in
   ...
   const userConnectionAuthedInRoom = app.channel(app.channels)
       .filter(connection => connection.user._id === params.user._id  && params.roomId === roomId);
   app.channel(roomId).join(userConnectionAuthedInRoom)
 
})
```
