### ISSUE TITLE
Authorization hooks are not transport agnostic.

### ISSUE THREAD

**Issue by antarasi** [feathersjs/feathers#755]
### Steps to reproduce
I prepared a repo with an example server app and test specs:
[https://github.com/antarasi/feathers-auth-test](https://github.com/antarasi/feathers-auth-test)

### Expected behavior
Authorization hooks should respond with the same message regardless of transport used. 

### Actual behavior
Authorization hooks produce different behavior when accessed from different transports. Moreover Socket.io has a small vulnerability not taking token expiration into account.

### System configuration
**Module versions** 
```
    "@feathersjs/authentication": "^2.1.0",
    "@feathersjs/authentication-jwt": "^1.0.1",
    "@feathersjs/authentication-local": "^1.0.2",
    "@feathersjs/client": "^3.1.1",
    "@feathersjs/feathers": "^3.0.2",
    "@feathersjs/socketio": "^3.0.1",
    "feathers-authentication-hooks": "^0.1.5",
    "socket.io-client": "^2.0.4",
```

**NodeJS version**: v8.9.3

**Operating System**: Windows 10

**Comment by daffl** [comment]
The `restrictToAuthenticated`, `verifyToken()` and `populateUser()`, hook is deprecated (documented in the [auth v1 migration guide](https://github.com/feathersjs/authentication/blob/master/docs/migrating.md)) and I am also planning on deprecating the rest of `feathers-authentication-hooks` because the other ones can be easily implemented in a few lines in a custom hook with all the flexibility you need.

**Comment by antarasi** [comment]
Hi @daffl. Thanks for explanation. I wasn't migrating from older version therefore I have not read this guide. I'm quite new in feathers so I expected that any deprecation warnings should appear in official documentation (https://docs.feathersjs.com/api/authentication/hooks.html) or in console upon startup.

**Comment by daffl** [comment]
Actually you are correct, I'm not sure why `restrictToAuthenticate` is even still kicking around in the current `feathers-authentication-hooks`. I will at least add a deprecation notice for that one because it `require('@feathersjs/authentication').hooks.authenticate(strategy)` already handles that.

**Comment by antarasi** [comment]
Thanks @daffl that would be useful as currently docs are ambiguous. Are you going to look into token expiration issue as well or am I missing something in how it should work?
