### ISSUE TITLE
data cannot show in feathers postgree

### ISSUE THREAD

**Issue by Juancesar123** [feathersjs/feathers#791]
i'm get data to table view in postgree using feathers but data not show, if i access API in feathers 

`// See http://docs.sequelizejs.com/en/latest/docs/models-definition/
// for more of what you can do here.
const Sequelize = require('sequelize');
const DataTypes = Sequelize.DataTypes;

module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient');
  const viewPortofolioHomeBalance = sequelizeClient.define('view_portofolio_home_balance', {
    cif: {
      type: DataTypes.STRING(50),
      allowNull: true,
      unique: true,
      primaryKey: true,
    },
    rekening: {
      type: DataTypes.STRING(50),
      allowNull: true
    },
    cif_id: {
      type: DataTypes.STRING(50),
      allowNull: true
    },
    balance_date: {
      type: DataTypes.DATE,
      allowNull: true
    },
    bank_type: {
      type: DataTypes.STRING(50),
      allowNull: true
    },
    ccy: {
      type: DataTypes.STRING(50),
      allowNull: true
    },
    balance_1: {
      type: DataTypes.DECIMAL(15, 2) ,
      allowNull: true
    },
    balance_2: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: true
    },
  }, {
    hooks: {
      beforeCount(options) {
        options.raw = true;
      }
    },
    schema:'portofolio',
    timestamps: false
  });

  viewPortofolioHomeBalance.associate = function (models) { // eslint-disable-line no-unused-vars
    // Define associations here
    // See http://docs.sequelizejs.com/en/latest/docs/associations/
  };

  return viewPortofolioHomeBalance;
};
`

**Comment by daffl** [comment]
What versions? Error messages? Do you have a reproducible example?

**Comment by daffl** [comment]
Hi there! We are happy to help but we need more information about your problem.

### Error message

Are you getting an error message?

### Steps to reproduce

__The best way to get help is to share a GitHub repository or code snippet with the minimal setup to reproduce your issue.__

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc. This makes it much easier for us to debug and issues that have a reproducable example will get higher priority.

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:
