### ISSUE TITLE
Generate Jest tests instead of Mocha?

### ISSUE THREAD

**Issue by danawoodman** [feathersjs/feathers#845]
Is there anything on the roadmap to support generating Jest tests instead of Mocha tests? Jest is getting quite popular and has become my defacto testing library. Right now Jest users will have to completely replace the generated tests. Perhaps a config option could be set and Feathers could generate Jest style tests instead? Just a thought!

**Comment by daffl** [comment]
It is not on the roadmap but as with most generator improvements, I would be happy to accept a pull request that adds it to the generator.

Test files are just generated (as in there is no code transformations) so it should be fairly straightforward, the only thing would be how to figure out what testing library the current project is using. This could probably be done by checking `const testLib = pkg.devDependecies.jest ? 'jest' : 'mocha';`

**Comment by rtyler** [comment]
In case anybody stumbles into this ticket some time before @danawoodman contributes a pull request :smiling_imp: , the only major change between using `jest` and `mocha` for feathersjs is changing `before(() => { });` and `after(() => { });` to `beforeEach` and `afterEach` respectively. (see [the jest documentation for more](https://facebook.github.io/jest/docs/en/setup-teardown.html)).

Otherwise the mocha-generated test  stubs are _pretty_ compatible out of the box.

**Comment by daffl** [comment]
This has been done via https://github.com/feathersjs/feathers/pull/1057

**Comment by eric-burel** [comment]
Hi,
Update from an existing app is not obvious so I'll post it here for googlers:
- add a script named `jest` in your package.json. Feathers cli will look for the existence of this script to select either jest or mocha (default); `"jest":"jest"`
- install Jest as a devDependency : `npm i --save-dev jest`

You're good to go, from now on the CLI will generate a jest test. Of course you'll need to update your old mocha tests for Jest.

Note that this does not sound either obvious or scalable to other test frameworks. I'd rather have an explicit "config" object (or even "feathers" if it's allowed?) in package.json to configure such choices, like it seems you did in a first iteration, instead of an auto-discovery.
Still, thanks a lot for this feature, using Jest is really pleasurable especially for full-stack since it's used a lot in the React ecosystem.
