### ISSUE TITLE
Use protect when not the absolute last hook?

### ISSUE THREAD

**Issue by mbt-jeremy-r** [feathersjs/feathers#847]
In my hooks setup, I have a global after hook add-envelope which wrap the data in a standardized schema sent to the client.

I also want to ensure some fields (password spring to mind) never get sent to the user.

My first thought was to use the `protect` hook, but that send the response without the envelope, since the response is sent right after the `protect` hook.

So my question is: Should I simply make a custom hook to remove the data I need to protect, or can I use the `protect` hook? Can I use protect to remove multiple fields?

**Comment by daffl** [comment]
When using the `protect` hook it will set [context.dispatch](https://docs.feathersjs.com/api/hooks.html#contextdispatch) to a safe version of `context.result`. So that it doesn't have to run last isn't entirely correct, it just has to run _after_ anything that modifies `context.result`.

If you make your standardized schema wrapper use (if available) and set `context.dispatch` it should work:

```js
const data = context.dispatch || context.result;

context.dispatch = wrapData(data);
```

`context.dispatch` will only be used by Feathers transports as the data to send to a client. If you want to use the same format internally you can set `context.result` and then set `context.dispatch = null;`
