### ISSUE TITLE
Change error object format

### ISSUE THREAD

**Issue by lozah** [feathersjs/feathers#850]
Hello !
I'm starting with feathersjs, and atm i'm stuck trying to modify the return error object ...

I've generated a new hook for all the application, linked to the error hook. like that 

```
error: {
    all: [logger(), handleError()],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
```

and in my handle error file did this : 

```
module.exports = function (options = {}) {
  return async context => {
    const error = context.error;
    context.error = new Error(error.message, {
      code: error.code
    })
    return context;
  };
};
```

So i just would like to have my object with status code and message but i still got : 

```
{
    "name": "GeneralError",
    "message": "Invalid login",
    "code": 500,
    "className": "general-error",
    "data": {},
    "errors": {}
}
```

(btw it changed status code from 400 to 500 and i don't know why ...)

I can't figure out what's happening.

Thank you !

**Comment by daffl** [comment]
This is the fallback of [Feathers Express error handler](https://docs.feathersjs.com/api/express.html#expresserrorhandler). If it doesn't get a [Feathers error](https://docs.feathersjs.com/api/errors.html) it will try and convert it to one. The reason is that standard JS errors are not serializable (the error you set will return `{}` when running through `JSON.stringify`).

There are [Feathers Errors](https://docs.feathersjs.com/api/errors.htm) for most use cases and you can also create your own [custom Feathers error](https://docs.feathersjs.com/api/errors.html#custom-errors).

**Comment by lozah** [comment]
Thank you for your fast response, 
I don't know how i could miss this part in the documentation ..
Custom errors will solve this :)
