### ISSUE TITLE
Feature request: Service names for nested routes

### ISSUE THREAD

**Issue by rottmann** [feathersjs/feathers#856]
Accessing a service by the route name is not really comfortable. Ok we can use constants for it, but it would be nice if it is implemented into feathers.

currently with a path:
`let service = app.service('users/:userId/verify')`

with a name it could look like:
`let service = app.service('userVerify')`

**Comment by daffl** [comment]
Thank you @rottmann. Feathers is a very modular framework so a lot of new features can be implemented as separate plugins that are usually also very small and easy to maintain. What you are suggesting could look like this:

```js
// aliases.js
module.exports = (aliases = {}) => {
  return app => {
    const oldService = app.service;

    Object.assign(app, {
      aliases,
      service(path, ...args) {
        const finalPath = this.aliases[path] ? this.aliases[path] : path;
        return oldService.call(this, finalPath, ...args);
      }
    })
  }
}

const aliases = require('./aliases');

app.configure(aliases({
  userVerify: 'users/:userId/verify'
}));
```

In general we prefer the plugin route whenever possible in order to keep Feathers core small and easy to maintain.

**Comment by rottmann** [comment]
Yes i think this solution is very good and keeps the core clean.
