### ISSUE TITLE
Move to Gitlab

### ISSUE THREAD

**Issue by rayfoss** [feathersjs/feathers#882]
### Steps to reproduce
Browse to the Feathers Repo website on Github

### Expected behavior
I should not be using a Microsoft product when using feathers

### Actual behavior
You'll be supporting and using a Microsoft product

### System configuration
Linux
Not Microsoft DOS

**Module versions** (especially the part that's not working):
All of them

**NodeJS version**:
Is anything sacred anymore

**Operating System**:
Not WIndows

**Browser Version**:
Not Internet Exploder 6

**React Native Version**:
Don't use :)

**Module Loader**:
Not Microsoft

**Comment by daffl** [comment]
I don't think this is a discussion worth having yet. I appreciate you suggesting alternatives but migrating _anything_ will be a very significant effort that I highly suspect will end up on _my_ plate and currently I don't foresee any major problems with who is hosting our open source code repositories.

**Comment by rayfoss** [comment]
https://www.youtube.com/watch?v=VYOXuOg9tQI 

I'll just drop this here

**Comment by daffl** [comment]
I think you are underestimating the impact of any of those changes. Even slightly changing the structure of the documentation turned out to be much more of a pain (I remember you being one of the people pointing that out several times 😉) than anticipated. There is a lot more to our infrastructure than where the code is hosted and it is all tied together.

I do care about the viability and ideology of open source but there are also compromises that have to be made for practical reasons. Frankly, I also really don't have the time to make a massive change like this for purely ideological reasons. What if Google ends up buying GitLab? Sometimes patience is the best course of action before switching anything especially in the open source world (Bower, Yarn or ioJS are just a few examples that come to mind).
