### ISSUE TITLE
Error reporting problem

### ISSUE THREAD

**Issue by goodluck81** [feathersjs/feathers#886]
Hello,

I have an unexplained problem, I just cloned one of my old project and changed the theme. Nothing changed on the server side, not a single line and still I have two types of error reporting:

Old project (expected behaviour):

<img width="993" alt="screen shot 2018-06-13 at 2 28 03 pm" src="https://user-images.githubusercontent.com/9041273/41351332-51fbcb04-6f16-11e8-8c88-5935f56e6922.png">
And the new project (folder "server" copy/paste):

<img width="1311" alt="screen shot 2018-06-13 at 2 30 02 pm" src="https://user-images.githubusercontent.com/9041273/41351345-5a21f6f0-6f16-11e8-89ef-8c86db54eed5.png">

https://gist.github.com/goodluck81/7238d0c5eea1e7cd8e069298f1db0163

I simply can't figure it out, please help

**Comment by daffl** [comment]
This can happen because newer, backwards compatible versions of the packages have been installed. It appears there is some Nuxt logging going on so you'll have to look where that is coming from.

For the Feathers application, almost all logging happens in `hooks/logger.js` so you can adjust your settings there. Additionally, the [Express errorHandler](https://docs.feathersjs.com/api/express.html#appuseexpresserrorhandleroptions) takes a `logger` option. The default is `console.error(error)`, if you don't want it to log, set `logger: false` in the `errorHandler` options.

**Comment by goodluck81** [comment]
I just commented the app.configure(middleware) (the nuxt middleware) and still same error type. Is funny (or not) because I use exactly the same featherjs/* package version, nuxt version, same env. Basically, I copied the "server" folder and error handler is different...

**Comment by daffl** [comment]
Well something has to be different 😉 If you have a repository that can reproduce the same issue from scratch it would be easier to look at, unfortunately the Gist doesn't have enough information.

**Comment by goodluck81** [comment]
I kinda fixed, but still unexplainable. I copied not working project files into another folder and worked. I can't explain this behaviour, if I duplicate the server project doesn't work, if I copy only files to another folder ... works.

**Comment by MartinBucko** [comment]
I create new issue. https://github.com/feathersjs/feathers/issues/887 
I think we have different problems. :)

**Comment by daffl** [comment]
I'm pretty certain this is the same as #887 because the latest versions or your dependencies got installed. As in my comment there (https://github.com/feathersjs/feathers/issues/887#issuecomment-397342812) changing `logger.error(context.error)` to `logger.error(context.error.stack)` in `hooks/logger.js` will fix this. Will update in the generator as well.
