### ISSUE TITLE
How to update user data?

### ISSUE THREAD

**Issue by lean** [feathersjs/feathers#898]
I have a backoffice with user roles and the admin needs to update some information of the users. When the admin do the update of some fields (for example, "type of client") the app respond with `BadRequest: notNull Violation: users.email cannot be null`.
How could I do to update some fields of the users?

**Comment by daffl** [comment]
To update partial data, [patch](https://docs.feathersjs.com/api/services.html#patchid-data-params) (db [adapter patch](https://docs.feathersjs.com/api/databases/common.html#adapterpatchid-data-params)) should be used instead of [update](https://docs.feathersjs.com/api/services.html#updateid-data-params).

**Comment by lean** [comment]
thanks!
