### ISSUE TITLE
How to determine if a call to a service was triggered on the server?

### ISSUE THREAD

**Issue by RickEyre** [feathersjs/feathers#920]
I'd like to run a hook globally, but only when the request I'm receiving has not come internally from another service.

It's an issue as I'm calling services within the hook that trigger this global hook and so it's an infinite loop.

Is this possible?

**Comment by daffl** [comment]
For external requests `params.provider` will be set. It is documented [here](https://docs.feathersjs.com/api/services.html#params), [here](https://docs.feathersjs.com/api/express.html#paramsprovider) and [here](https://docs.feathersjs.com/api/socketio.html#paramsprovider). Note that `params.provider` can also be set explicitly for internal requests. This usually happens when passing through `params` from an external request. If that is not what you want it has to be omitted explicitly.

**Comment by RickEyre** [comment]
Okay great, thank you. Also, sorry, I should have read the documentation more clearly.
