### ISSUE TITLE
how to modify reponse header

### ISSUE THREAD

**Issue by mohitmayank** [feathersjs/feathers#999]
how can i modify response headers? writing express middleware after the app.configure(services); doesn thelp. 
I am trying to add a Location header on post requests with the created resource's url.

**Comment by daffl** [comment]
The [Feathers Express API chapter](https://docs.feathersjs.com/api/express.html) documents two possibilities:

1) A [global formatter](https://docs.feathersjs.com/api/express.html#appconfigureexpressrestformatter) that applies to all services
2) A [custom middleware registered after the service](https://docs.feathersjs.com/api/express.html#custom-service-middleware) that applies to an individual service

**Comment by mohitmayank** [comment]
thanks a lot. I did use this approach. i was just hoping for a way to do this in hooks. perhaps this can be in faq?

**Comment by daffl** [comment]
Maybe we can make it part of the [How do I access the request object in hooks or services?](https://docs.feathersjs.com/faq/readme.html#how-do-i-access-the-request-object-in-hooks-or-services) FAQ.
Generally, because Feathers is protocol agnostic, anything transport specific (in this case the headers for HTTP requests) should go into the transport layer bindings. For example, individual websockets requests don't really have a concept of HTTP headers all.
